// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Auth.proto

package com.proto;

public final class Auth {
  private Auth() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MceAuthOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MceAuth)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *名字
     * </pre>
     *
     * <code>optional string id = 1 [default = ""];</code>
     */
    boolean hasId();
    /**
     * <pre>
     *名字
     * </pre>
     *
     * <code>optional string id = 1 [default = ""];</code>
     */
    java.lang.String getId();
    /**
     * <pre>
     *名字
     * </pre>
     *
     * <code>optional string id = 1 [default = ""];</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional string pass = 2;</code>
     */
    boolean hasPass();
    /**
     * <code>optional string pass = 2;</code>
     */
    java.lang.String getPass();
    /**
     * <code>optional string pass = 2;</code>
     */
    com.google.protobuf.ByteString
        getPassBytes();
  }
  /**
   * Protobuf type {@code MceAuth}
   */
  public  static final class MceAuth extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MceAuth)
      MceAuthOrBuilder {
    // Use MceAuth.newBuilder() to construct.
    private MceAuth(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MceAuth() {
      id_ = "";
      pass_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MceAuth(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              pass_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.proto.Auth.internal_static_MceAuth_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.proto.Auth.internal_static_MceAuth_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.proto.Auth.MceAuth.class, com.proto.Auth.MceAuth.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <pre>
     *名字
     * </pre>
     *
     * <code>optional string id = 1 [default = ""];</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *名字
     * </pre>
     *
     * <code>optional string id = 1 [default = ""];</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *名字
     * </pre>
     *
     * <code>optional string id = 1 [default = ""];</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASS_FIELD_NUMBER = 2;
    private volatile java.lang.Object pass_;
    /**
     * <code>optional string pass = 2;</code>
     */
    public boolean hasPass() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string pass = 2;</code>
     */
    public java.lang.String getPass() {
      java.lang.Object ref = pass_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pass_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string pass = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPassBytes() {
      java.lang.Object ref = pass_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, pass_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, pass_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.proto.Auth.MceAuth)) {
        return super.equals(obj);
      }
      com.proto.Auth.MceAuth other = (com.proto.Auth.MceAuth) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && getId()
            .equals(other.getId());
      }
      result = result && (hasPass() == other.hasPass());
      if (hasPass()) {
        result = result && getPass()
            .equals(other.getPass());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (hasPass()) {
        hash = (37 * hash) + PASS_FIELD_NUMBER;
        hash = (53 * hash) + getPass().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.proto.Auth.MceAuth parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.Auth.MceAuth parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.Auth.MceAuth parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.Auth.MceAuth parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.Auth.MceAuth parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.proto.Auth.MceAuth parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.proto.Auth.MceAuth parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.proto.Auth.MceAuth parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.proto.Auth.MceAuth parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.proto.Auth.MceAuth parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.proto.Auth.MceAuth prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MceAuth}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MceAuth)
        com.proto.Auth.MceAuthOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.proto.Auth.internal_static_MceAuth_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.proto.Auth.internal_static_MceAuth_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.proto.Auth.MceAuth.class, com.proto.Auth.MceAuth.Builder.class);
      }

      // Construct using com.proto.Auth.MceAuth.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        pass_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.proto.Auth.internal_static_MceAuth_descriptor;
      }

      public com.proto.Auth.MceAuth getDefaultInstanceForType() {
        return com.proto.Auth.MceAuth.getDefaultInstance();
      }

      public com.proto.Auth.MceAuth build() {
        com.proto.Auth.MceAuth result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.proto.Auth.MceAuth buildPartial() {
        com.proto.Auth.MceAuth result = new com.proto.Auth.MceAuth(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pass_ = pass_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.proto.Auth.MceAuth) {
          return mergeFrom((com.proto.Auth.MceAuth)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.proto.Auth.MceAuth other) {
        if (other == com.proto.Auth.MceAuth.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasPass()) {
          bitField0_ |= 0x00000002;
          pass_ = other.pass_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.proto.Auth.MceAuth parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.proto.Auth.MceAuth) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <pre>
       *名字
       * </pre>
       *
       * <code>optional string id = 1 [default = ""];</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *名字
       * </pre>
       *
       * <code>optional string id = 1 [default = ""];</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *名字
       * </pre>
       *
       * <code>optional string id = 1 [default = ""];</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *名字
       * </pre>
       *
       * <code>optional string id = 1 [default = ""];</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *名字
       * </pre>
       *
       * <code>optional string id = 1 [default = ""];</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *名字
       * </pre>
       *
       * <code>optional string id = 1 [default = ""];</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object pass_ = "";
      /**
       * <code>optional string pass = 2;</code>
       */
      public boolean hasPass() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string pass = 2;</code>
       */
      public java.lang.String getPass() {
        java.lang.Object ref = pass_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            pass_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string pass = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPassBytes() {
        java.lang.Object ref = pass_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pass_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string pass = 2;</code>
       */
      public Builder setPass(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        pass_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string pass = 2;</code>
       */
      public Builder clearPass() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pass_ = getDefaultInstance().getPass();
        onChanged();
        return this;
      }
      /**
       * <code>optional string pass = 2;</code>
       */
      public Builder setPassBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        pass_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MceAuth)
    }

    // @@protoc_insertion_point(class_scope:MceAuth)
    private static final com.proto.Auth.MceAuth DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.proto.Auth.MceAuth();
    }

    public static com.proto.Auth.MceAuth getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MceAuth>
        PARSER = new com.google.protobuf.AbstractParser<MceAuth>() {
      public MceAuth parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MceAuth(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MceAuth> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MceAuth> getParserForType() {
      return PARSER;
    }

    public com.proto.Auth.MceAuth getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MseAuthOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MseAuth)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string uid = 1;</code>
     */
    boolean hasUid();
    /**
     * <code>optional string uid = 1;</code>
     */
    java.lang.String getUid();
    /**
     * <code>optional string uid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUidBytes();

    /**
     * <code>optional bool succ = 2;</code>
     */
    boolean hasSucc();
    /**
     * <code>optional bool succ = 2;</code>
     */
    boolean getSucc();

    /**
     * <code>optional bool redirect = 3 [default = false];</code>
     */
    boolean hasRedirect();
    /**
     * <code>optional bool redirect = 3 [default = false];</code>
     */
    boolean getRedirect();

    /**
     * <code>optional string redirect_port = 4;</code>
     */
    boolean hasRedirectPort();
    /**
     * <code>optional string redirect_port = 4;</code>
     */
    java.lang.String getRedirectPort();
    /**
     * <code>optional string redirect_port = 4;</code>
     */
    com.google.protobuf.ByteString
        getRedirectPortBytes();

    /**
     * <code>optional string redirect_ip = 5;</code>
     */
    boolean hasRedirectIp();
    /**
     * <code>optional string redirect_ip = 5;</code>
     */
    java.lang.String getRedirectIp();
    /**
     * <code>optional string redirect_ip = 5;</code>
     */
    com.google.protobuf.ByteString
        getRedirectIpBytes();

    /**
     * <code>optional string redirect_pass = 6;</code>
     */
    boolean hasRedirectPass();
    /**
     * <code>optional string redirect_pass = 6;</code>
     */
    java.lang.String getRedirectPass();
    /**
     * <code>optional string redirect_pass = 6;</code>
     */
    com.google.protobuf.ByteString
        getRedirectPassBytes();

    /**
     * <code>optional string name = 7;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 7;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 7;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional bool bIsNew = 8;</code>
     */
    boolean hasBIsNew();
    /**
     * <code>optional bool bIsNew = 8;</code>
     */
    boolean getBIsNew();

    /**
     * <pre>
     *推荐的国家
     * </pre>
     *
     * <code>optional int32 nCamp = 9;</code>
     */
    boolean hasNCamp();
    /**
     * <pre>
     *推荐的国家
     * </pre>
     *
     * <code>optional int32 nCamp = 9;</code>
     */
    int getNCamp();
  }
  /**
   * Protobuf type {@code MseAuth}
   */
  public  static final class MseAuth extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MseAuth)
      MseAuthOrBuilder {
    // Use MseAuth.newBuilder() to construct.
    private MseAuth(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MseAuth() {
      uid_ = "";
      succ_ = false;
      redirect_ = false;
      redirectPort_ = "";
      redirectIp_ = "";
      redirectPass_ = "";
      name_ = "";
      bIsNew_ = false;
      nCamp_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MseAuth(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              uid_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              succ_ = input.readBool();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              redirect_ = input.readBool();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              redirectPort_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              redirectIp_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              redirectPass_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              name_ = bs;
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              bIsNew_ = input.readBool();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              nCamp_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.proto.Auth.internal_static_MseAuth_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.proto.Auth.internal_static_MseAuth_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.proto.Auth.MseAuth.class, com.proto.Auth.MseAuth.Builder.class);
    }

    private int bitField0_;
    public static final int UID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uid_;
    /**
     * <code>optional string uid = 1;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string uid = 1;</code>
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string uid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUCC_FIELD_NUMBER = 2;
    private boolean succ_;
    /**
     * <code>optional bool succ = 2;</code>
     */
    public boolean hasSucc() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool succ = 2;</code>
     */
    public boolean getSucc() {
      return succ_;
    }

    public static final int REDIRECT_FIELD_NUMBER = 3;
    private boolean redirect_;
    /**
     * <code>optional bool redirect = 3 [default = false];</code>
     */
    public boolean hasRedirect() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool redirect = 3 [default = false];</code>
     */
    public boolean getRedirect() {
      return redirect_;
    }

    public static final int REDIRECT_PORT_FIELD_NUMBER = 4;
    private volatile java.lang.Object redirectPort_;
    /**
     * <code>optional string redirect_port = 4;</code>
     */
    public boolean hasRedirectPort() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string redirect_port = 4;</code>
     */
    public java.lang.String getRedirectPort() {
      java.lang.Object ref = redirectPort_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          redirectPort_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string redirect_port = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRedirectPortBytes() {
      java.lang.Object ref = redirectPort_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        redirectPort_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REDIRECT_IP_FIELD_NUMBER = 5;
    private volatile java.lang.Object redirectIp_;
    /**
     * <code>optional string redirect_ip = 5;</code>
     */
    public boolean hasRedirectIp() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string redirect_ip = 5;</code>
     */
    public java.lang.String getRedirectIp() {
      java.lang.Object ref = redirectIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          redirectIp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string redirect_ip = 5;</code>
     */
    public com.google.protobuf.ByteString
        getRedirectIpBytes() {
      java.lang.Object ref = redirectIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        redirectIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REDIRECT_PASS_FIELD_NUMBER = 6;
    private volatile java.lang.Object redirectPass_;
    /**
     * <code>optional string redirect_pass = 6;</code>
     */
    public boolean hasRedirectPass() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string redirect_pass = 6;</code>
     */
    public java.lang.String getRedirectPass() {
      java.lang.Object ref = redirectPass_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          redirectPass_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string redirect_pass = 6;</code>
     */
    public com.google.protobuf.ByteString
        getRedirectPassBytes() {
      java.lang.Object ref = redirectPass_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        redirectPass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 7;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 7;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string name = 7;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 7;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BISNEW_FIELD_NUMBER = 8;
    private boolean bIsNew_;
    /**
     * <code>optional bool bIsNew = 8;</code>
     */
    public boolean hasBIsNew() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional bool bIsNew = 8;</code>
     */
    public boolean getBIsNew() {
      return bIsNew_;
    }

    public static final int NCAMP_FIELD_NUMBER = 9;
    private int nCamp_;
    /**
     * <pre>
     *推荐的国家
     * </pre>
     *
     * <code>optional int32 nCamp = 9;</code>
     */
    public boolean hasNCamp() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <pre>
     *推荐的国家
     * </pre>
     *
     * <code>optional int32 nCamp = 9;</code>
     */
    public int getNCamp() {
      return nCamp_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, succ_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, redirect_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, redirectPort_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, redirectIp_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, redirectPass_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, name_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBool(8, bIsNew_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, nCamp_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, succ_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, redirect_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, redirectPort_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, redirectIp_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, redirectPass_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, name_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, bIsNew_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, nCamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.proto.Auth.MseAuth)) {
        return super.equals(obj);
      }
      com.proto.Auth.MseAuth other = (com.proto.Auth.MseAuth) obj;

      boolean result = true;
      result = result && (hasUid() == other.hasUid());
      if (hasUid()) {
        result = result && getUid()
            .equals(other.getUid());
      }
      result = result && (hasSucc() == other.hasSucc());
      if (hasSucc()) {
        result = result && (getSucc()
            == other.getSucc());
      }
      result = result && (hasRedirect() == other.hasRedirect());
      if (hasRedirect()) {
        result = result && (getRedirect()
            == other.getRedirect());
      }
      result = result && (hasRedirectPort() == other.hasRedirectPort());
      if (hasRedirectPort()) {
        result = result && getRedirectPort()
            .equals(other.getRedirectPort());
      }
      result = result && (hasRedirectIp() == other.hasRedirectIp());
      if (hasRedirectIp()) {
        result = result && getRedirectIp()
            .equals(other.getRedirectIp());
      }
      result = result && (hasRedirectPass() == other.hasRedirectPass());
      if (hasRedirectPass()) {
        result = result && getRedirectPass()
            .equals(other.getRedirectPass());
      }
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasBIsNew() == other.hasBIsNew());
      if (hasBIsNew()) {
        result = result && (getBIsNew()
            == other.getBIsNew());
      }
      result = result && (hasNCamp() == other.hasNCamp());
      if (hasNCamp()) {
        result = result && (getNCamp()
            == other.getNCamp());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasUid()) {
        hash = (37 * hash) + UID_FIELD_NUMBER;
        hash = (53 * hash) + getUid().hashCode();
      }
      if (hasSucc()) {
        hash = (37 * hash) + SUCC_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getSucc());
      }
      if (hasRedirect()) {
        hash = (37 * hash) + REDIRECT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getRedirect());
      }
      if (hasRedirectPort()) {
        hash = (37 * hash) + REDIRECT_PORT_FIELD_NUMBER;
        hash = (53 * hash) + getRedirectPort().hashCode();
      }
      if (hasRedirectIp()) {
        hash = (37 * hash) + REDIRECT_IP_FIELD_NUMBER;
        hash = (53 * hash) + getRedirectIp().hashCode();
      }
      if (hasRedirectPass()) {
        hash = (37 * hash) + REDIRECT_PASS_FIELD_NUMBER;
        hash = (53 * hash) + getRedirectPass().hashCode();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasBIsNew()) {
        hash = (37 * hash) + BISNEW_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getBIsNew());
      }
      if (hasNCamp()) {
        hash = (37 * hash) + NCAMP_FIELD_NUMBER;
        hash = (53 * hash) + getNCamp();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.proto.Auth.MseAuth parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.Auth.MseAuth parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.Auth.MseAuth parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.Auth.MseAuth parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.Auth.MseAuth parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.proto.Auth.MseAuth parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.proto.Auth.MseAuth parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.proto.Auth.MseAuth parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.proto.Auth.MseAuth parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.proto.Auth.MseAuth parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.proto.Auth.MseAuth prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MseAuth}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MseAuth)
        com.proto.Auth.MseAuthOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.proto.Auth.internal_static_MseAuth_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.proto.Auth.internal_static_MseAuth_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.proto.Auth.MseAuth.class, com.proto.Auth.MseAuth.Builder.class);
      }

      // Construct using com.proto.Auth.MseAuth.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        succ_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        redirect_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        redirectPort_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        redirectIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        redirectPass_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        bIsNew_ = false;
        bitField0_ = (bitField0_ & ~0x00000080);
        nCamp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.proto.Auth.internal_static_MseAuth_descriptor;
      }

      public com.proto.Auth.MseAuth getDefaultInstanceForType() {
        return com.proto.Auth.MseAuth.getDefaultInstance();
      }

      public com.proto.Auth.MseAuth build() {
        com.proto.Auth.MseAuth result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.proto.Auth.MseAuth buildPartial() {
        com.proto.Auth.MseAuth result = new com.proto.Auth.MseAuth(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.succ_ = succ_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.redirect_ = redirect_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.redirectPort_ = redirectPort_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.redirectIp_ = redirectIp_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.redirectPass_ = redirectPass_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.bIsNew_ = bIsNew_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.nCamp_ = nCamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.proto.Auth.MseAuth) {
          return mergeFrom((com.proto.Auth.MseAuth)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.proto.Auth.MseAuth other) {
        if (other == com.proto.Auth.MseAuth.getDefaultInstance()) return this;
        if (other.hasUid()) {
          bitField0_ |= 0x00000001;
          uid_ = other.uid_;
          onChanged();
        }
        if (other.hasSucc()) {
          setSucc(other.getSucc());
        }
        if (other.hasRedirect()) {
          setRedirect(other.getRedirect());
        }
        if (other.hasRedirectPort()) {
          bitField0_ |= 0x00000008;
          redirectPort_ = other.redirectPort_;
          onChanged();
        }
        if (other.hasRedirectIp()) {
          bitField0_ |= 0x00000010;
          redirectIp_ = other.redirectIp_;
          onChanged();
        }
        if (other.hasRedirectPass()) {
          bitField0_ |= 0x00000020;
          redirectPass_ = other.redirectPass_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000040;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasBIsNew()) {
          setBIsNew(other.getBIsNew());
        }
        if (other.hasNCamp()) {
          setNCamp(other.getNCamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.proto.Auth.MseAuth parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.proto.Auth.MseAuth) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object uid_ = "";
      /**
       * <code>optional string uid = 1;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string uid = 1;</code>
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string uid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string uid = 1;</code>
       */
      public Builder setUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string uid = 1;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string uid = 1;</code>
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }

      private boolean succ_ ;
      /**
       * <code>optional bool succ = 2;</code>
       */
      public boolean hasSucc() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool succ = 2;</code>
       */
      public boolean getSucc() {
        return succ_;
      }
      /**
       * <code>optional bool succ = 2;</code>
       */
      public Builder setSucc(boolean value) {
        bitField0_ |= 0x00000002;
        succ_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool succ = 2;</code>
       */
      public Builder clearSucc() {
        bitField0_ = (bitField0_ & ~0x00000002);
        succ_ = false;
        onChanged();
        return this;
      }

      private boolean redirect_ ;
      /**
       * <code>optional bool redirect = 3 [default = false];</code>
       */
      public boolean hasRedirect() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool redirect = 3 [default = false];</code>
       */
      public boolean getRedirect() {
        return redirect_;
      }
      /**
       * <code>optional bool redirect = 3 [default = false];</code>
       */
      public Builder setRedirect(boolean value) {
        bitField0_ |= 0x00000004;
        redirect_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool redirect = 3 [default = false];</code>
       */
      public Builder clearRedirect() {
        bitField0_ = (bitField0_ & ~0x00000004);
        redirect_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object redirectPort_ = "";
      /**
       * <code>optional string redirect_port = 4;</code>
       */
      public boolean hasRedirectPort() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string redirect_port = 4;</code>
       */
      public java.lang.String getRedirectPort() {
        java.lang.Object ref = redirectPort_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            redirectPort_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string redirect_port = 4;</code>
       */
      public com.google.protobuf.ByteString
          getRedirectPortBytes() {
        java.lang.Object ref = redirectPort_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          redirectPort_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string redirect_port = 4;</code>
       */
      public Builder setRedirectPort(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        redirectPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string redirect_port = 4;</code>
       */
      public Builder clearRedirectPort() {
        bitField0_ = (bitField0_ & ~0x00000008);
        redirectPort_ = getDefaultInstance().getRedirectPort();
        onChanged();
        return this;
      }
      /**
       * <code>optional string redirect_port = 4;</code>
       */
      public Builder setRedirectPortBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        redirectPort_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object redirectIp_ = "";
      /**
       * <code>optional string redirect_ip = 5;</code>
       */
      public boolean hasRedirectIp() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string redirect_ip = 5;</code>
       */
      public java.lang.String getRedirectIp() {
        java.lang.Object ref = redirectIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            redirectIp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string redirect_ip = 5;</code>
       */
      public com.google.protobuf.ByteString
          getRedirectIpBytes() {
        java.lang.Object ref = redirectIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          redirectIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string redirect_ip = 5;</code>
       */
      public Builder setRedirectIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        redirectIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string redirect_ip = 5;</code>
       */
      public Builder clearRedirectIp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        redirectIp_ = getDefaultInstance().getRedirectIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string redirect_ip = 5;</code>
       */
      public Builder setRedirectIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        redirectIp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object redirectPass_ = "";
      /**
       * <code>optional string redirect_pass = 6;</code>
       */
      public boolean hasRedirectPass() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string redirect_pass = 6;</code>
       */
      public java.lang.String getRedirectPass() {
        java.lang.Object ref = redirectPass_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            redirectPass_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string redirect_pass = 6;</code>
       */
      public com.google.protobuf.ByteString
          getRedirectPassBytes() {
        java.lang.Object ref = redirectPass_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          redirectPass_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string redirect_pass = 6;</code>
       */
      public Builder setRedirectPass(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        redirectPass_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string redirect_pass = 6;</code>
       */
      public Builder clearRedirectPass() {
        bitField0_ = (bitField0_ & ~0x00000020);
        redirectPass_ = getDefaultInstance().getRedirectPass();
        onChanged();
        return this;
      }
      /**
       * <code>optional string redirect_pass = 6;</code>
       */
      public Builder setRedirectPassBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        redirectPass_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 7;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string name = 7;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 7;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 7;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 7;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000040);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 7;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        name_ = value;
        onChanged();
        return this;
      }

      private boolean bIsNew_ ;
      /**
       * <code>optional bool bIsNew = 8;</code>
       */
      public boolean hasBIsNew() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional bool bIsNew = 8;</code>
       */
      public boolean getBIsNew() {
        return bIsNew_;
      }
      /**
       * <code>optional bool bIsNew = 8;</code>
       */
      public Builder setBIsNew(boolean value) {
        bitField0_ |= 0x00000080;
        bIsNew_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool bIsNew = 8;</code>
       */
      public Builder clearBIsNew() {
        bitField0_ = (bitField0_ & ~0x00000080);
        bIsNew_ = false;
        onChanged();
        return this;
      }

      private int nCamp_ ;
      /**
       * <pre>
       *推荐的国家
       * </pre>
       *
       * <code>optional int32 nCamp = 9;</code>
       */
      public boolean hasNCamp() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <pre>
       *推荐的国家
       * </pre>
       *
       * <code>optional int32 nCamp = 9;</code>
       */
      public int getNCamp() {
        return nCamp_;
      }
      /**
       * <pre>
       *推荐的国家
       * </pre>
       *
       * <code>optional int32 nCamp = 9;</code>
       */
      public Builder setNCamp(int value) {
        bitField0_ |= 0x00000100;
        nCamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *推荐的国家
       * </pre>
       *
       * <code>optional int32 nCamp = 9;</code>
       */
      public Builder clearNCamp() {
        bitField0_ = (bitField0_ & ~0x00000100);
        nCamp_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MseAuth)
    }

    // @@protoc_insertion_point(class_scope:MseAuth)
    private static final com.proto.Auth.MseAuth DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.proto.Auth.MseAuth();
    }

    public static com.proto.Auth.MseAuth getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MseAuth>
        PARSER = new com.google.protobuf.AbstractParser<MseAuth>() {
      public MseAuth parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MseAuth(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MseAuth> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MseAuth> getParserForType() {
      return PARSER;
    }

    public com.proto.Auth.MseAuth getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MceAuth_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MceAuth_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MseAuth_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MseAuth_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nAuth.proto\"%\n\007MceAuth\022\014\n\002id\030\001 \001(\t:\000\022\014\n" +
      "\004pass\030\002 \001(\t\"\255\001\n\007MseAuth\022\013\n\003uid\030\001 \001(\t\022\014\n\004" +
      "succ\030\002 \001(\010\022\027\n\010redirect\030\003 \001(\010:\005false\022\025\n\rr" +
      "edirect_port\030\004 \001(\t\022\023\n\013redirect_ip\030\005 \001(\t\022" +
      "\025\n\rredirect_pass\030\006 \001(\t\022\014\n\004name\030\007 \001(\t\022\016\n\006" +
      "bIsNew\030\010 \001(\010\022\r\n\005nCamp\030\t \001(\005B\021\n\tcom.proto" +
      "B\004Auth"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MceAuth_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MceAuth_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MceAuth_descriptor,
        new java.lang.String[] { "Id", "Pass", });
    internal_static_MseAuth_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MseAuth_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MseAuth_descriptor,
        new java.lang.String[] { "Uid", "Succ", "Redirect", "RedirectPort", "RedirectIp", "RedirectPass", "Name", "BIsNew", "NCamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
