// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SceneObjDisappear.proto

package com.proto;

public final class SceneObjDisappear {
  private SceneObjDisappear() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MseSceneObjDisappearOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MseSceneObjDisappear)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string uid = 1;</code>
     */
    boolean hasUid();
    /**
     * <code>required string uid = 1;</code>
     */
    java.lang.String getUid();
    /**
     * <code>required string uid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUidBytes();
  }
  /**
   * <pre>
   *场景中的怪物信息
   * </pre>
   *
   * Protobuf type {@code MseSceneObjDisappear}
   */
  public  static final class MseSceneObjDisappear extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MseSceneObjDisappear)
      MseSceneObjDisappearOrBuilder {
    // Use MseSceneObjDisappear.newBuilder() to construct.
    private MseSceneObjDisappear(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MseSceneObjDisappear() {
      uid_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MseSceneObjDisappear(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              uid_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.proto.SceneObjDisappear.internal_static_MseSceneObjDisappear_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.proto.SceneObjDisappear.internal_static_MseSceneObjDisappear_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.proto.SceneObjDisappear.MseSceneObjDisappear.class, com.proto.SceneObjDisappear.MseSceneObjDisappear.Builder.class);
    }

    private int bitField0_;
    public static final int UID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uid_;
    /**
     * <code>required string uid = 1;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string uid = 1;</code>
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string uid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uid_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.proto.SceneObjDisappear.MseSceneObjDisappear)) {
        return super.equals(obj);
      }
      com.proto.SceneObjDisappear.MseSceneObjDisappear other = (com.proto.SceneObjDisappear.MseSceneObjDisappear) obj;

      boolean result = true;
      result = result && (hasUid() == other.hasUid());
      if (hasUid()) {
        result = result && getUid()
            .equals(other.getUid());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasUid()) {
        hash = (37 * hash) + UID_FIELD_NUMBER;
        hash = (53 * hash) + getUid().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.proto.SceneObjDisappear.MseSceneObjDisappear parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.SceneObjDisappear.MseSceneObjDisappear parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.SceneObjDisappear.MseSceneObjDisappear parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.SceneObjDisappear.MseSceneObjDisappear parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.SceneObjDisappear.MseSceneObjDisappear parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.proto.SceneObjDisappear.MseSceneObjDisappear parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.proto.SceneObjDisappear.MseSceneObjDisappear parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.proto.SceneObjDisappear.MseSceneObjDisappear parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.proto.SceneObjDisappear.MseSceneObjDisappear parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.proto.SceneObjDisappear.MseSceneObjDisappear parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.proto.SceneObjDisappear.MseSceneObjDisappear prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *场景中的怪物信息
     * </pre>
     *
     * Protobuf type {@code MseSceneObjDisappear}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MseSceneObjDisappear)
        com.proto.SceneObjDisappear.MseSceneObjDisappearOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.proto.SceneObjDisappear.internal_static_MseSceneObjDisappear_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.proto.SceneObjDisappear.internal_static_MseSceneObjDisappear_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.proto.SceneObjDisappear.MseSceneObjDisappear.class, com.proto.SceneObjDisappear.MseSceneObjDisappear.Builder.class);
      }

      // Construct using com.proto.SceneObjDisappear.MseSceneObjDisappear.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.proto.SceneObjDisappear.internal_static_MseSceneObjDisappear_descriptor;
      }

      public com.proto.SceneObjDisappear.MseSceneObjDisappear getDefaultInstanceForType() {
        return com.proto.SceneObjDisappear.MseSceneObjDisappear.getDefaultInstance();
      }

      public com.proto.SceneObjDisappear.MseSceneObjDisappear build() {
        com.proto.SceneObjDisappear.MseSceneObjDisappear result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.proto.SceneObjDisappear.MseSceneObjDisappear buildPartial() {
        com.proto.SceneObjDisappear.MseSceneObjDisappear result = new com.proto.SceneObjDisappear.MseSceneObjDisappear(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uid_ = uid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.proto.SceneObjDisappear.MseSceneObjDisappear) {
          return mergeFrom((com.proto.SceneObjDisappear.MseSceneObjDisappear)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.proto.SceneObjDisappear.MseSceneObjDisappear other) {
        if (other == com.proto.SceneObjDisappear.MseSceneObjDisappear.getDefaultInstance()) return this;
        if (other.hasUid()) {
          bitField0_ |= 0x00000001;
          uid_ = other.uid_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUid()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.proto.SceneObjDisappear.MseSceneObjDisappear parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.proto.SceneObjDisappear.MseSceneObjDisappear) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object uid_ = "";
      /**
       * <code>required string uid = 1;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string uid = 1;</code>
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string uid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string uid = 1;</code>
       */
      public Builder setUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string uid = 1;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <code>required string uid = 1;</code>
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MseSceneObjDisappear)
    }

    // @@protoc_insertion_point(class_scope:MseSceneObjDisappear)
    private static final com.proto.SceneObjDisappear.MseSceneObjDisappear DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.proto.SceneObjDisappear.MseSceneObjDisappear();
    }

    public static com.proto.SceneObjDisappear.MseSceneObjDisappear getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MseSceneObjDisappear>
        PARSER = new com.google.protobuf.AbstractParser<MseSceneObjDisappear>() {
      public MseSceneObjDisappear parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MseSceneObjDisappear(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MseSceneObjDisappear> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MseSceneObjDisappear> getParserForType() {
      return PARSER;
    }

    public com.proto.SceneObjDisappear.MseSceneObjDisappear getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MseSceneObjDisappearListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MseSceneObjDisappearList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .MseSceneObjDisappear sceneObjDisappear = 1;</code>
     */
    java.util.List<com.proto.SceneObjDisappear.MseSceneObjDisappear> 
        getSceneObjDisappearList();
    /**
     * <code>repeated .MseSceneObjDisappear sceneObjDisappear = 1;</code>
     */
    com.proto.SceneObjDisappear.MseSceneObjDisappear getSceneObjDisappear(int index);
    /**
     * <code>repeated .MseSceneObjDisappear sceneObjDisappear = 1;</code>
     */
    int getSceneObjDisappearCount();
    /**
     * <code>repeated .MseSceneObjDisappear sceneObjDisappear = 1;</code>
     */
    java.util.List<? extends com.proto.SceneObjDisappear.MseSceneObjDisappearOrBuilder> 
        getSceneObjDisappearOrBuilderList();
    /**
     * <code>repeated .MseSceneObjDisappear sceneObjDisappear = 1;</code>
     */
    com.proto.SceneObjDisappear.MseSceneObjDisappearOrBuilder getSceneObjDisappearOrBuilder(
        int index);
  }
  /**
   * <pre>
   * 场景中的怪物列表
   * </pre>
   *
   * Protobuf type {@code MseSceneObjDisappearList}
   */
  public  static final class MseSceneObjDisappearList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MseSceneObjDisappearList)
      MseSceneObjDisappearListOrBuilder {
    // Use MseSceneObjDisappearList.newBuilder() to construct.
    private MseSceneObjDisappearList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MseSceneObjDisappearList() {
      sceneObjDisappear_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MseSceneObjDisappearList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                sceneObjDisappear_ = new java.util.ArrayList<com.proto.SceneObjDisappear.MseSceneObjDisappear>();
                mutable_bitField0_ |= 0x00000001;
              }
              sceneObjDisappear_.add(
                  input.readMessage(com.proto.SceneObjDisappear.MseSceneObjDisappear.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          sceneObjDisappear_ = java.util.Collections.unmodifiableList(sceneObjDisappear_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.proto.SceneObjDisappear.internal_static_MseSceneObjDisappearList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.proto.SceneObjDisappear.internal_static_MseSceneObjDisappearList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.proto.SceneObjDisappear.MseSceneObjDisappearList.class, com.proto.SceneObjDisappear.MseSceneObjDisappearList.Builder.class);
    }

    public static final int SCENEOBJDISAPPEAR_FIELD_NUMBER = 1;
    private java.util.List<com.proto.SceneObjDisappear.MseSceneObjDisappear> sceneObjDisappear_;
    /**
     * <code>repeated .MseSceneObjDisappear sceneObjDisappear = 1;</code>
     */
    public java.util.List<com.proto.SceneObjDisappear.MseSceneObjDisappear> getSceneObjDisappearList() {
      return sceneObjDisappear_;
    }
    /**
     * <code>repeated .MseSceneObjDisappear sceneObjDisappear = 1;</code>
     */
    public java.util.List<? extends com.proto.SceneObjDisappear.MseSceneObjDisappearOrBuilder> 
        getSceneObjDisappearOrBuilderList() {
      return sceneObjDisappear_;
    }
    /**
     * <code>repeated .MseSceneObjDisappear sceneObjDisappear = 1;</code>
     */
    public int getSceneObjDisappearCount() {
      return sceneObjDisappear_.size();
    }
    /**
     * <code>repeated .MseSceneObjDisappear sceneObjDisappear = 1;</code>
     */
    public com.proto.SceneObjDisappear.MseSceneObjDisappear getSceneObjDisappear(int index) {
      return sceneObjDisappear_.get(index);
    }
    /**
     * <code>repeated .MseSceneObjDisappear sceneObjDisappear = 1;</code>
     */
    public com.proto.SceneObjDisappear.MseSceneObjDisappearOrBuilder getSceneObjDisappearOrBuilder(
        int index) {
      return sceneObjDisappear_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getSceneObjDisappearCount(); i++) {
        if (!getSceneObjDisappear(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < sceneObjDisappear_.size(); i++) {
        output.writeMessage(1, sceneObjDisappear_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < sceneObjDisappear_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, sceneObjDisappear_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.proto.SceneObjDisappear.MseSceneObjDisappearList)) {
        return super.equals(obj);
      }
      com.proto.SceneObjDisappear.MseSceneObjDisappearList other = (com.proto.SceneObjDisappear.MseSceneObjDisappearList) obj;

      boolean result = true;
      result = result && getSceneObjDisappearList()
          .equals(other.getSceneObjDisappearList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getSceneObjDisappearCount() > 0) {
        hash = (37 * hash) + SCENEOBJDISAPPEAR_FIELD_NUMBER;
        hash = (53 * hash) + getSceneObjDisappearList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.proto.SceneObjDisappear.MseSceneObjDisappearList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.SceneObjDisappear.MseSceneObjDisappearList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.SceneObjDisappear.MseSceneObjDisappearList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.SceneObjDisappear.MseSceneObjDisappearList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.SceneObjDisappear.MseSceneObjDisappearList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.proto.SceneObjDisappear.MseSceneObjDisappearList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.proto.SceneObjDisappear.MseSceneObjDisappearList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.proto.SceneObjDisappear.MseSceneObjDisappearList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.proto.SceneObjDisappear.MseSceneObjDisappearList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.proto.SceneObjDisappear.MseSceneObjDisappearList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.proto.SceneObjDisappear.MseSceneObjDisappearList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 场景中的怪物列表
     * </pre>
     *
     * Protobuf type {@code MseSceneObjDisappearList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MseSceneObjDisappearList)
        com.proto.SceneObjDisappear.MseSceneObjDisappearListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.proto.SceneObjDisappear.internal_static_MseSceneObjDisappearList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.proto.SceneObjDisappear.internal_static_MseSceneObjDisappearList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.proto.SceneObjDisappear.MseSceneObjDisappearList.class, com.proto.SceneObjDisappear.MseSceneObjDisappearList.Builder.class);
      }

      // Construct using com.proto.SceneObjDisappear.MseSceneObjDisappearList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSceneObjDisappearFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (sceneObjDisappearBuilder_ == null) {
          sceneObjDisappear_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          sceneObjDisappearBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.proto.SceneObjDisappear.internal_static_MseSceneObjDisappearList_descriptor;
      }

      public com.proto.SceneObjDisappear.MseSceneObjDisappearList getDefaultInstanceForType() {
        return com.proto.SceneObjDisappear.MseSceneObjDisappearList.getDefaultInstance();
      }

      public com.proto.SceneObjDisappear.MseSceneObjDisappearList build() {
        com.proto.SceneObjDisappear.MseSceneObjDisappearList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.proto.SceneObjDisappear.MseSceneObjDisappearList buildPartial() {
        com.proto.SceneObjDisappear.MseSceneObjDisappearList result = new com.proto.SceneObjDisappear.MseSceneObjDisappearList(this);
        int from_bitField0_ = bitField0_;
        if (sceneObjDisappearBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            sceneObjDisappear_ = java.util.Collections.unmodifiableList(sceneObjDisappear_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.sceneObjDisappear_ = sceneObjDisappear_;
        } else {
          result.sceneObjDisappear_ = sceneObjDisappearBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.proto.SceneObjDisappear.MseSceneObjDisappearList) {
          return mergeFrom((com.proto.SceneObjDisappear.MseSceneObjDisappearList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.proto.SceneObjDisappear.MseSceneObjDisappearList other) {
        if (other == com.proto.SceneObjDisappear.MseSceneObjDisappearList.getDefaultInstance()) return this;
        if (sceneObjDisappearBuilder_ == null) {
          if (!other.sceneObjDisappear_.isEmpty()) {
            if (sceneObjDisappear_.isEmpty()) {
              sceneObjDisappear_ = other.sceneObjDisappear_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSceneObjDisappearIsMutable();
              sceneObjDisappear_.addAll(other.sceneObjDisappear_);
            }
            onChanged();
          }
        } else {
          if (!other.sceneObjDisappear_.isEmpty()) {
            if (sceneObjDisappearBuilder_.isEmpty()) {
              sceneObjDisappearBuilder_.dispose();
              sceneObjDisappearBuilder_ = null;
              sceneObjDisappear_ = other.sceneObjDisappear_;
              bitField0_ = (bitField0_ & ~0x00000001);
              sceneObjDisappearBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSceneObjDisappearFieldBuilder() : null;
            } else {
              sceneObjDisappearBuilder_.addAllMessages(other.sceneObjDisappear_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getSceneObjDisappearCount(); i++) {
          if (!getSceneObjDisappear(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.proto.SceneObjDisappear.MseSceneObjDisappearList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.proto.SceneObjDisappear.MseSceneObjDisappearList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.proto.SceneObjDisappear.MseSceneObjDisappear> sceneObjDisappear_ =
        java.util.Collections.emptyList();
      private void ensureSceneObjDisappearIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          sceneObjDisappear_ = new java.util.ArrayList<com.proto.SceneObjDisappear.MseSceneObjDisappear>(sceneObjDisappear_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.proto.SceneObjDisappear.MseSceneObjDisappear, com.proto.SceneObjDisappear.MseSceneObjDisappear.Builder, com.proto.SceneObjDisappear.MseSceneObjDisappearOrBuilder> sceneObjDisappearBuilder_;

      /**
       * <code>repeated .MseSceneObjDisappear sceneObjDisappear = 1;</code>
       */
      public java.util.List<com.proto.SceneObjDisappear.MseSceneObjDisappear> getSceneObjDisappearList() {
        if (sceneObjDisappearBuilder_ == null) {
          return java.util.Collections.unmodifiableList(sceneObjDisappear_);
        } else {
          return sceneObjDisappearBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .MseSceneObjDisappear sceneObjDisappear = 1;</code>
       */
      public int getSceneObjDisappearCount() {
        if (sceneObjDisappearBuilder_ == null) {
          return sceneObjDisappear_.size();
        } else {
          return sceneObjDisappearBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .MseSceneObjDisappear sceneObjDisappear = 1;</code>
       */
      public com.proto.SceneObjDisappear.MseSceneObjDisappear getSceneObjDisappear(int index) {
        if (sceneObjDisappearBuilder_ == null) {
          return sceneObjDisappear_.get(index);
        } else {
          return sceneObjDisappearBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .MseSceneObjDisappear sceneObjDisappear = 1;</code>
       */
      public Builder setSceneObjDisappear(
          int index, com.proto.SceneObjDisappear.MseSceneObjDisappear value) {
        if (sceneObjDisappearBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSceneObjDisappearIsMutable();
          sceneObjDisappear_.set(index, value);
          onChanged();
        } else {
          sceneObjDisappearBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MseSceneObjDisappear sceneObjDisappear = 1;</code>
       */
      public Builder setSceneObjDisappear(
          int index, com.proto.SceneObjDisappear.MseSceneObjDisappear.Builder builderForValue) {
        if (sceneObjDisappearBuilder_ == null) {
          ensureSceneObjDisappearIsMutable();
          sceneObjDisappear_.set(index, builderForValue.build());
          onChanged();
        } else {
          sceneObjDisappearBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MseSceneObjDisappear sceneObjDisappear = 1;</code>
       */
      public Builder addSceneObjDisappear(com.proto.SceneObjDisappear.MseSceneObjDisappear value) {
        if (sceneObjDisappearBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSceneObjDisappearIsMutable();
          sceneObjDisappear_.add(value);
          onChanged();
        } else {
          sceneObjDisappearBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .MseSceneObjDisappear sceneObjDisappear = 1;</code>
       */
      public Builder addSceneObjDisappear(
          int index, com.proto.SceneObjDisappear.MseSceneObjDisappear value) {
        if (sceneObjDisappearBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSceneObjDisappearIsMutable();
          sceneObjDisappear_.add(index, value);
          onChanged();
        } else {
          sceneObjDisappearBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MseSceneObjDisappear sceneObjDisappear = 1;</code>
       */
      public Builder addSceneObjDisappear(
          com.proto.SceneObjDisappear.MseSceneObjDisappear.Builder builderForValue) {
        if (sceneObjDisappearBuilder_ == null) {
          ensureSceneObjDisappearIsMutable();
          sceneObjDisappear_.add(builderForValue.build());
          onChanged();
        } else {
          sceneObjDisappearBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MseSceneObjDisappear sceneObjDisappear = 1;</code>
       */
      public Builder addSceneObjDisappear(
          int index, com.proto.SceneObjDisappear.MseSceneObjDisappear.Builder builderForValue) {
        if (sceneObjDisappearBuilder_ == null) {
          ensureSceneObjDisappearIsMutable();
          sceneObjDisappear_.add(index, builderForValue.build());
          onChanged();
        } else {
          sceneObjDisappearBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MseSceneObjDisappear sceneObjDisappear = 1;</code>
       */
      public Builder addAllSceneObjDisappear(
          java.lang.Iterable<? extends com.proto.SceneObjDisappear.MseSceneObjDisappear> values) {
        if (sceneObjDisappearBuilder_ == null) {
          ensureSceneObjDisappearIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, sceneObjDisappear_);
          onChanged();
        } else {
          sceneObjDisappearBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .MseSceneObjDisappear sceneObjDisappear = 1;</code>
       */
      public Builder clearSceneObjDisappear() {
        if (sceneObjDisappearBuilder_ == null) {
          sceneObjDisappear_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          sceneObjDisappearBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .MseSceneObjDisappear sceneObjDisappear = 1;</code>
       */
      public Builder removeSceneObjDisappear(int index) {
        if (sceneObjDisappearBuilder_ == null) {
          ensureSceneObjDisappearIsMutable();
          sceneObjDisappear_.remove(index);
          onChanged();
        } else {
          sceneObjDisappearBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .MseSceneObjDisappear sceneObjDisappear = 1;</code>
       */
      public com.proto.SceneObjDisappear.MseSceneObjDisappear.Builder getSceneObjDisappearBuilder(
          int index) {
        return getSceneObjDisappearFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .MseSceneObjDisappear sceneObjDisappear = 1;</code>
       */
      public com.proto.SceneObjDisappear.MseSceneObjDisappearOrBuilder getSceneObjDisappearOrBuilder(
          int index) {
        if (sceneObjDisappearBuilder_ == null) {
          return sceneObjDisappear_.get(index);  } else {
          return sceneObjDisappearBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .MseSceneObjDisappear sceneObjDisappear = 1;</code>
       */
      public java.util.List<? extends com.proto.SceneObjDisappear.MseSceneObjDisappearOrBuilder> 
           getSceneObjDisappearOrBuilderList() {
        if (sceneObjDisappearBuilder_ != null) {
          return sceneObjDisappearBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(sceneObjDisappear_);
        }
      }
      /**
       * <code>repeated .MseSceneObjDisappear sceneObjDisappear = 1;</code>
       */
      public com.proto.SceneObjDisappear.MseSceneObjDisappear.Builder addSceneObjDisappearBuilder() {
        return getSceneObjDisappearFieldBuilder().addBuilder(
            com.proto.SceneObjDisappear.MseSceneObjDisappear.getDefaultInstance());
      }
      /**
       * <code>repeated .MseSceneObjDisappear sceneObjDisappear = 1;</code>
       */
      public com.proto.SceneObjDisappear.MseSceneObjDisappear.Builder addSceneObjDisappearBuilder(
          int index) {
        return getSceneObjDisappearFieldBuilder().addBuilder(
            index, com.proto.SceneObjDisappear.MseSceneObjDisappear.getDefaultInstance());
      }
      /**
       * <code>repeated .MseSceneObjDisappear sceneObjDisappear = 1;</code>
       */
      public java.util.List<com.proto.SceneObjDisappear.MseSceneObjDisappear.Builder> 
           getSceneObjDisappearBuilderList() {
        return getSceneObjDisappearFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.proto.SceneObjDisappear.MseSceneObjDisappear, com.proto.SceneObjDisappear.MseSceneObjDisappear.Builder, com.proto.SceneObjDisappear.MseSceneObjDisappearOrBuilder> 
          getSceneObjDisappearFieldBuilder() {
        if (sceneObjDisappearBuilder_ == null) {
          sceneObjDisappearBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.proto.SceneObjDisappear.MseSceneObjDisappear, com.proto.SceneObjDisappear.MseSceneObjDisappear.Builder, com.proto.SceneObjDisappear.MseSceneObjDisappearOrBuilder>(
                  sceneObjDisappear_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          sceneObjDisappear_ = null;
        }
        return sceneObjDisappearBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MseSceneObjDisappearList)
    }

    // @@protoc_insertion_point(class_scope:MseSceneObjDisappearList)
    private static final com.proto.SceneObjDisappear.MseSceneObjDisappearList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.proto.SceneObjDisappear.MseSceneObjDisappearList();
    }

    public static com.proto.SceneObjDisappear.MseSceneObjDisappearList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MseSceneObjDisappearList>
        PARSER = new com.google.protobuf.AbstractParser<MseSceneObjDisappearList>() {
      public MseSceneObjDisappearList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MseSceneObjDisappearList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MseSceneObjDisappearList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MseSceneObjDisappearList> getParserForType() {
      return PARSER;
    }

    public com.proto.SceneObjDisappear.MseSceneObjDisappearList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MseSceneObjDisappear_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MseSceneObjDisappear_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MseSceneObjDisappearList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MseSceneObjDisappearList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027SceneObjDisappear.proto\"#\n\024MseSceneObj" +
      "Disappear\022\013\n\003uid\030\001 \002(\t\"L\n\030MseSceneObjDis" +
      "appearList\0220\n\021sceneObjDisappear\030\001 \003(\0132\025." +
      "MseSceneObjDisappearB\036\n\tcom.protoB\021Scene" +
      "ObjDisappear"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MseSceneObjDisappear_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MseSceneObjDisappear_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MseSceneObjDisappear_descriptor,
        new java.lang.String[] { "Uid", });
    internal_static_MseSceneObjDisappearList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MseSceneObjDisappearList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MseSceneObjDisappearList_descriptor,
        new java.lang.String[] { "SceneObjDisappear", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
