// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SceneObjMove.proto

package com.proto;

public final class SceneObjMove {
  private SceneObjMove() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code E_SceneObjMoveS}
   */
  public enum E_SceneObjMoveS
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *停止
     * </pre>
     *
     * <code>STOP = 1;</code>
     */
    STOP(1),
    /**
     * <pre>
     *原地转
     * </pre>
     *
     * <code>STOP_AND_ROTATE = 2;</code>
     */
    STOP_AND_ROTATE(2),
    /**
     * <pre>
     *移动不转向
     * </pre>
     *
     * <code>MOVE = 3;</code>
     */
    MOVE(3),
    /**
     * <pre>
     *移动并转向
     * </pre>
     *
     * <code>MOVE_AND_ROTATE = 4;</code>
     */
    MOVE_AND_ROTATE(4),
    ;

    /**
     * <pre>
     *停止
     * </pre>
     *
     * <code>STOP = 1;</code>
     */
    public static final int STOP_VALUE = 1;
    /**
     * <pre>
     *原地转
     * </pre>
     *
     * <code>STOP_AND_ROTATE = 2;</code>
     */
    public static final int STOP_AND_ROTATE_VALUE = 2;
    /**
     * <pre>
     *移动不转向
     * </pre>
     *
     * <code>MOVE = 3;</code>
     */
    public static final int MOVE_VALUE = 3;
    /**
     * <pre>
     *移动并转向
     * </pre>
     *
     * <code>MOVE_AND_ROTATE = 4;</code>
     */
    public static final int MOVE_AND_ROTATE_VALUE = 4;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static E_SceneObjMoveS valueOf(int value) {
      return forNumber(value);
    }

    public static E_SceneObjMoveS forNumber(int value) {
      switch (value) {
        case 1: return STOP;
        case 2: return STOP_AND_ROTATE;
        case 3: return MOVE;
        case 4: return MOVE_AND_ROTATE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<E_SceneObjMoveS>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        E_SceneObjMoveS> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<E_SceneObjMoveS>() {
            public E_SceneObjMoveS findValueByNumber(int number) {
              return E_SceneObjMoveS.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.proto.SceneObjMove.getDescriptor().getEnumTypes().get(0);
    }

    private static final E_SceneObjMoveS[] VALUES = values();

    public static E_SceneObjMoveS valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private E_SceneObjMoveS(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:E_SceneObjMoveS)
  }

  public interface MseSceneObjMoveOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MseSceneObjMove)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string uid = 1;</code>
     */
    boolean hasUid();
    /**
     * <code>required string uid = 1;</code>
     */
    java.lang.String getUid();
    /**
     * <code>required string uid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUidBytes();

    /**
     * <code>required .E_SceneObjMoveS status = 2;</code>
     */
    boolean hasStatus();
    /**
     * <code>required .E_SceneObjMoveS status = 2;</code>
     */
    com.proto.SceneObjMove.E_SceneObjMoveS getStatus();

    /**
     * <code>required int64 endTime = 3;</code>
     */
    boolean hasEndTime();
    /**
     * <code>required int64 endTime = 3;</code>
     */
    long getEndTime();

    /**
     * <code>optional float posX = 4;</code>
     */
    boolean hasPosX();
    /**
     * <code>optional float posX = 4;</code>
     */
    float getPosX();

    /**
     * <code>optional float posY = 5;</code>
     */
    boolean hasPosY();
    /**
     * <code>optional float posY = 5;</code>
     */
    float getPosY();

    /**
     * <code>optional float currentDegree = 6;</code>
     */
    boolean hasCurrentDegree();
    /**
     * <code>optional float currentDegree = 6;</code>
     */
    float getCurrentDegree();

    /**
     * <code>optional float targetDegree = 7;</code>
     */
    boolean hasTargetDegree();
    /**
     * <code>optional float targetDegree = 7;</code>
     */
    float getTargetDegree();
  }
  /**
   * <pre>
   *场景中的怪物信息
   * </pre>
   *
   * Protobuf type {@code MseSceneObjMove}
   */
  public  static final class MseSceneObjMove extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MseSceneObjMove)
      MseSceneObjMoveOrBuilder {
    // Use MseSceneObjMove.newBuilder() to construct.
    private MseSceneObjMove(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MseSceneObjMove() {
      uid_ = "";
      status_ = 1;
      endTime_ = 0L;
      posX_ = 0F;
      posY_ = 0F;
      currentDegree_ = 0F;
      targetDegree_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MseSceneObjMove(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              uid_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.proto.SceneObjMove.E_SceneObjMoveS value = com.proto.SceneObjMove.E_SceneObjMoveS.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                status_ = rawValue;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              endTime_ = input.readInt64();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              posX_ = input.readFloat();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000010;
              posY_ = input.readFloat();
              break;
            }
            case 53: {
              bitField0_ |= 0x00000020;
              currentDegree_ = input.readFloat();
              break;
            }
            case 61: {
              bitField0_ |= 0x00000040;
              targetDegree_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.proto.SceneObjMove.internal_static_MseSceneObjMove_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.proto.SceneObjMove.internal_static_MseSceneObjMove_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.proto.SceneObjMove.MseSceneObjMove.class, com.proto.SceneObjMove.MseSceneObjMove.Builder.class);
    }

    private int bitField0_;
    public static final int UID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uid_;
    /**
     * <code>required string uid = 1;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string uid = 1;</code>
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string uid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private int status_;
    /**
     * <code>required .E_SceneObjMoveS status = 2;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .E_SceneObjMoveS status = 2;</code>
     */
    public com.proto.SceneObjMove.E_SceneObjMoveS getStatus() {
      com.proto.SceneObjMove.E_SceneObjMoveS result = com.proto.SceneObjMove.E_SceneObjMoveS.valueOf(status_);
      return result == null ? com.proto.SceneObjMove.E_SceneObjMoveS.STOP : result;
    }

    public static final int ENDTIME_FIELD_NUMBER = 3;
    private long endTime_;
    /**
     * <code>required int64 endTime = 3;</code>
     */
    public boolean hasEndTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 endTime = 3;</code>
     */
    public long getEndTime() {
      return endTime_;
    }

    public static final int POSX_FIELD_NUMBER = 4;
    private float posX_;
    /**
     * <code>optional float posX = 4;</code>
     */
    public boolean hasPosX() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional float posX = 4;</code>
     */
    public float getPosX() {
      return posX_;
    }

    public static final int POSY_FIELD_NUMBER = 5;
    private float posY_;
    /**
     * <code>optional float posY = 5;</code>
     */
    public boolean hasPosY() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional float posY = 5;</code>
     */
    public float getPosY() {
      return posY_;
    }

    public static final int CURRENTDEGREE_FIELD_NUMBER = 6;
    private float currentDegree_;
    /**
     * <code>optional float currentDegree = 6;</code>
     */
    public boolean hasCurrentDegree() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional float currentDegree = 6;</code>
     */
    public float getCurrentDegree() {
      return currentDegree_;
    }

    public static final int TARGETDEGREE_FIELD_NUMBER = 7;
    private float targetDegree_;
    /**
     * <code>optional float targetDegree = 7;</code>
     */
    public boolean hasTargetDegree() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional float targetDegree = 7;</code>
     */
    public float getTargetDegree() {
      return targetDegree_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEndTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, status_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, endTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, posX_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeFloat(5, posY_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeFloat(6, currentDegree_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeFloat(7, targetDegree_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, status_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, endTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, posX_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, posY_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, currentDegree_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, targetDegree_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.proto.SceneObjMove.MseSceneObjMove)) {
        return super.equals(obj);
      }
      com.proto.SceneObjMove.MseSceneObjMove other = (com.proto.SceneObjMove.MseSceneObjMove) obj;

      boolean result = true;
      result = result && (hasUid() == other.hasUid());
      if (hasUid()) {
        result = result && getUid()
            .equals(other.getUid());
      }
      result = result && (hasStatus() == other.hasStatus());
      if (hasStatus()) {
        result = result && status_ == other.status_;
      }
      result = result && (hasEndTime() == other.hasEndTime());
      if (hasEndTime()) {
        result = result && (getEndTime()
            == other.getEndTime());
      }
      result = result && (hasPosX() == other.hasPosX());
      if (hasPosX()) {
        result = result && (
            java.lang.Float.floatToIntBits(getPosX())
            == java.lang.Float.floatToIntBits(
                other.getPosX()));
      }
      result = result && (hasPosY() == other.hasPosY());
      if (hasPosY()) {
        result = result && (
            java.lang.Float.floatToIntBits(getPosY())
            == java.lang.Float.floatToIntBits(
                other.getPosY()));
      }
      result = result && (hasCurrentDegree() == other.hasCurrentDegree());
      if (hasCurrentDegree()) {
        result = result && (
            java.lang.Float.floatToIntBits(getCurrentDegree())
            == java.lang.Float.floatToIntBits(
                other.getCurrentDegree()));
      }
      result = result && (hasTargetDegree() == other.hasTargetDegree());
      if (hasTargetDegree()) {
        result = result && (
            java.lang.Float.floatToIntBits(getTargetDegree())
            == java.lang.Float.floatToIntBits(
                other.getTargetDegree()));
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasUid()) {
        hash = (37 * hash) + UID_FIELD_NUMBER;
        hash = (53 * hash) + getUid().hashCode();
      }
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + status_;
      }
      if (hasEndTime()) {
        hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getEndTime());
      }
      if (hasPosX()) {
        hash = (37 * hash) + POSX_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getPosX());
      }
      if (hasPosY()) {
        hash = (37 * hash) + POSY_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getPosY());
      }
      if (hasCurrentDegree()) {
        hash = (37 * hash) + CURRENTDEGREE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getCurrentDegree());
      }
      if (hasTargetDegree()) {
        hash = (37 * hash) + TARGETDEGREE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getTargetDegree());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.proto.SceneObjMove.MseSceneObjMove parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.SceneObjMove.MseSceneObjMove parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.SceneObjMove.MseSceneObjMove parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.SceneObjMove.MseSceneObjMove parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.SceneObjMove.MseSceneObjMove parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.proto.SceneObjMove.MseSceneObjMove parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.proto.SceneObjMove.MseSceneObjMove parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.proto.SceneObjMove.MseSceneObjMove parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.proto.SceneObjMove.MseSceneObjMove parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.proto.SceneObjMove.MseSceneObjMove parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.proto.SceneObjMove.MseSceneObjMove prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *场景中的怪物信息
     * </pre>
     *
     * Protobuf type {@code MseSceneObjMove}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MseSceneObjMove)
        com.proto.SceneObjMove.MseSceneObjMoveOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.proto.SceneObjMove.internal_static_MseSceneObjMove_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.proto.SceneObjMove.internal_static_MseSceneObjMove_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.proto.SceneObjMove.MseSceneObjMove.class, com.proto.SceneObjMove.MseSceneObjMove.Builder.class);
      }

      // Construct using com.proto.SceneObjMove.MseSceneObjMove.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 1;
        bitField0_ = (bitField0_ & ~0x00000002);
        endTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        posX_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        posY_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        currentDegree_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000020);
        targetDegree_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.proto.SceneObjMove.internal_static_MseSceneObjMove_descriptor;
      }

      public com.proto.SceneObjMove.MseSceneObjMove getDefaultInstanceForType() {
        return com.proto.SceneObjMove.MseSceneObjMove.getDefaultInstance();
      }

      public com.proto.SceneObjMove.MseSceneObjMove build() {
        com.proto.SceneObjMove.MseSceneObjMove result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.proto.SceneObjMove.MseSceneObjMove buildPartial() {
        com.proto.SceneObjMove.MseSceneObjMove result = new com.proto.SceneObjMove.MseSceneObjMove(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.endTime_ = endTime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.posX_ = posX_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.posY_ = posY_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.currentDegree_ = currentDegree_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.targetDegree_ = targetDegree_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.proto.SceneObjMove.MseSceneObjMove) {
          return mergeFrom((com.proto.SceneObjMove.MseSceneObjMove)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.proto.SceneObjMove.MseSceneObjMove other) {
        if (other == com.proto.SceneObjMove.MseSceneObjMove.getDefaultInstance()) return this;
        if (other.hasUid()) {
          bitField0_ |= 0x00000001;
          uid_ = other.uid_;
          onChanged();
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasEndTime()) {
          setEndTime(other.getEndTime());
        }
        if (other.hasPosX()) {
          setPosX(other.getPosX());
        }
        if (other.hasPosY()) {
          setPosY(other.getPosY());
        }
        if (other.hasCurrentDegree()) {
          setCurrentDegree(other.getCurrentDegree());
        }
        if (other.hasTargetDegree()) {
          setTargetDegree(other.getTargetDegree());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUid()) {
          return false;
        }
        if (!hasStatus()) {
          return false;
        }
        if (!hasEndTime()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.proto.SceneObjMove.MseSceneObjMove parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.proto.SceneObjMove.MseSceneObjMove) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object uid_ = "";
      /**
       * <code>required string uid = 1;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string uid = 1;</code>
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string uid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string uid = 1;</code>
       */
      public Builder setUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string uid = 1;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <code>required string uid = 1;</code>
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }

      private int status_ = 1;
      /**
       * <code>required .E_SceneObjMoveS status = 2;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .E_SceneObjMoveS status = 2;</code>
       */
      public com.proto.SceneObjMove.E_SceneObjMoveS getStatus() {
        com.proto.SceneObjMove.E_SceneObjMoveS result = com.proto.SceneObjMove.E_SceneObjMoveS.valueOf(status_);
        return result == null ? com.proto.SceneObjMove.E_SceneObjMoveS.STOP : result;
      }
      /**
       * <code>required .E_SceneObjMoveS status = 2;</code>
       */
      public Builder setStatus(com.proto.SceneObjMove.E_SceneObjMoveS value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .E_SceneObjMoveS status = 2;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = 1;
        onChanged();
        return this;
      }

      private long endTime_ ;
      /**
       * <code>required int64 endTime = 3;</code>
       */
      public boolean hasEndTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 endTime = 3;</code>
       */
      public long getEndTime() {
        return endTime_;
      }
      /**
       * <code>required int64 endTime = 3;</code>
       */
      public Builder setEndTime(long value) {
        bitField0_ |= 0x00000004;
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 endTime = 3;</code>
       */
      public Builder clearEndTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        endTime_ = 0L;
        onChanged();
        return this;
      }

      private float posX_ ;
      /**
       * <code>optional float posX = 4;</code>
       */
      public boolean hasPosX() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional float posX = 4;</code>
       */
      public float getPosX() {
        return posX_;
      }
      /**
       * <code>optional float posX = 4;</code>
       */
      public Builder setPosX(float value) {
        bitField0_ |= 0x00000008;
        posX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float posX = 4;</code>
       */
      public Builder clearPosX() {
        bitField0_ = (bitField0_ & ~0x00000008);
        posX_ = 0F;
        onChanged();
        return this;
      }

      private float posY_ ;
      /**
       * <code>optional float posY = 5;</code>
       */
      public boolean hasPosY() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional float posY = 5;</code>
       */
      public float getPosY() {
        return posY_;
      }
      /**
       * <code>optional float posY = 5;</code>
       */
      public Builder setPosY(float value) {
        bitField0_ |= 0x00000010;
        posY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float posY = 5;</code>
       */
      public Builder clearPosY() {
        bitField0_ = (bitField0_ & ~0x00000010);
        posY_ = 0F;
        onChanged();
        return this;
      }

      private float currentDegree_ ;
      /**
       * <code>optional float currentDegree = 6;</code>
       */
      public boolean hasCurrentDegree() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional float currentDegree = 6;</code>
       */
      public float getCurrentDegree() {
        return currentDegree_;
      }
      /**
       * <code>optional float currentDegree = 6;</code>
       */
      public Builder setCurrentDegree(float value) {
        bitField0_ |= 0x00000020;
        currentDegree_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float currentDegree = 6;</code>
       */
      public Builder clearCurrentDegree() {
        bitField0_ = (bitField0_ & ~0x00000020);
        currentDegree_ = 0F;
        onChanged();
        return this;
      }

      private float targetDegree_ ;
      /**
       * <code>optional float targetDegree = 7;</code>
       */
      public boolean hasTargetDegree() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional float targetDegree = 7;</code>
       */
      public float getTargetDegree() {
        return targetDegree_;
      }
      /**
       * <code>optional float targetDegree = 7;</code>
       */
      public Builder setTargetDegree(float value) {
        bitField0_ |= 0x00000040;
        targetDegree_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float targetDegree = 7;</code>
       */
      public Builder clearTargetDegree() {
        bitField0_ = (bitField0_ & ~0x00000040);
        targetDegree_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MseSceneObjMove)
    }

    // @@protoc_insertion_point(class_scope:MseSceneObjMove)
    private static final com.proto.SceneObjMove.MseSceneObjMove DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.proto.SceneObjMove.MseSceneObjMove();
    }

    public static com.proto.SceneObjMove.MseSceneObjMove getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MseSceneObjMove>
        PARSER = new com.google.protobuf.AbstractParser<MseSceneObjMove>() {
      public MseSceneObjMove parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MseSceneObjMove(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MseSceneObjMove> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MseSceneObjMove> getParserForType() {
      return PARSER;
    }

    public com.proto.SceneObjMove.MseSceneObjMove getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MseSceneObjMoveListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MseSceneObjMoveList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .MseSceneObjMove sceneObjMove = 1;</code>
     */
    java.util.List<com.proto.SceneObjMove.MseSceneObjMove> 
        getSceneObjMoveList();
    /**
     * <code>repeated .MseSceneObjMove sceneObjMove = 1;</code>
     */
    com.proto.SceneObjMove.MseSceneObjMove getSceneObjMove(int index);
    /**
     * <code>repeated .MseSceneObjMove sceneObjMove = 1;</code>
     */
    int getSceneObjMoveCount();
    /**
     * <code>repeated .MseSceneObjMove sceneObjMove = 1;</code>
     */
    java.util.List<? extends com.proto.SceneObjMove.MseSceneObjMoveOrBuilder> 
        getSceneObjMoveOrBuilderList();
    /**
     * <code>repeated .MseSceneObjMove sceneObjMove = 1;</code>
     */
    com.proto.SceneObjMove.MseSceneObjMoveOrBuilder getSceneObjMoveOrBuilder(
        int index);
  }
  /**
   * <pre>
   * 场景中的怪物列表
   * </pre>
   *
   * Protobuf type {@code MseSceneObjMoveList}
   */
  public  static final class MseSceneObjMoveList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MseSceneObjMoveList)
      MseSceneObjMoveListOrBuilder {
    // Use MseSceneObjMoveList.newBuilder() to construct.
    private MseSceneObjMoveList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MseSceneObjMoveList() {
      sceneObjMove_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MseSceneObjMoveList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                sceneObjMove_ = new java.util.ArrayList<com.proto.SceneObjMove.MseSceneObjMove>();
                mutable_bitField0_ |= 0x00000001;
              }
              sceneObjMove_.add(
                  input.readMessage(com.proto.SceneObjMove.MseSceneObjMove.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          sceneObjMove_ = java.util.Collections.unmodifiableList(sceneObjMove_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.proto.SceneObjMove.internal_static_MseSceneObjMoveList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.proto.SceneObjMove.internal_static_MseSceneObjMoveList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.proto.SceneObjMove.MseSceneObjMoveList.class, com.proto.SceneObjMove.MseSceneObjMoveList.Builder.class);
    }

    public static final int SCENEOBJMOVE_FIELD_NUMBER = 1;
    private java.util.List<com.proto.SceneObjMove.MseSceneObjMove> sceneObjMove_;
    /**
     * <code>repeated .MseSceneObjMove sceneObjMove = 1;</code>
     */
    public java.util.List<com.proto.SceneObjMove.MseSceneObjMove> getSceneObjMoveList() {
      return sceneObjMove_;
    }
    /**
     * <code>repeated .MseSceneObjMove sceneObjMove = 1;</code>
     */
    public java.util.List<? extends com.proto.SceneObjMove.MseSceneObjMoveOrBuilder> 
        getSceneObjMoveOrBuilderList() {
      return sceneObjMove_;
    }
    /**
     * <code>repeated .MseSceneObjMove sceneObjMove = 1;</code>
     */
    public int getSceneObjMoveCount() {
      return sceneObjMove_.size();
    }
    /**
     * <code>repeated .MseSceneObjMove sceneObjMove = 1;</code>
     */
    public com.proto.SceneObjMove.MseSceneObjMove getSceneObjMove(int index) {
      return sceneObjMove_.get(index);
    }
    /**
     * <code>repeated .MseSceneObjMove sceneObjMove = 1;</code>
     */
    public com.proto.SceneObjMove.MseSceneObjMoveOrBuilder getSceneObjMoveOrBuilder(
        int index) {
      return sceneObjMove_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getSceneObjMoveCount(); i++) {
        if (!getSceneObjMove(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < sceneObjMove_.size(); i++) {
        output.writeMessage(1, sceneObjMove_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < sceneObjMove_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, sceneObjMove_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.proto.SceneObjMove.MseSceneObjMoveList)) {
        return super.equals(obj);
      }
      com.proto.SceneObjMove.MseSceneObjMoveList other = (com.proto.SceneObjMove.MseSceneObjMoveList) obj;

      boolean result = true;
      result = result && getSceneObjMoveList()
          .equals(other.getSceneObjMoveList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getSceneObjMoveCount() > 0) {
        hash = (37 * hash) + SCENEOBJMOVE_FIELD_NUMBER;
        hash = (53 * hash) + getSceneObjMoveList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.proto.SceneObjMove.MseSceneObjMoveList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.SceneObjMove.MseSceneObjMoveList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.SceneObjMove.MseSceneObjMoveList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.SceneObjMove.MseSceneObjMoveList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.SceneObjMove.MseSceneObjMoveList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.proto.SceneObjMove.MseSceneObjMoveList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.proto.SceneObjMove.MseSceneObjMoveList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.proto.SceneObjMove.MseSceneObjMoveList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.proto.SceneObjMove.MseSceneObjMoveList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.proto.SceneObjMove.MseSceneObjMoveList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.proto.SceneObjMove.MseSceneObjMoveList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 场景中的怪物列表
     * </pre>
     *
     * Protobuf type {@code MseSceneObjMoveList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MseSceneObjMoveList)
        com.proto.SceneObjMove.MseSceneObjMoveListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.proto.SceneObjMove.internal_static_MseSceneObjMoveList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.proto.SceneObjMove.internal_static_MseSceneObjMoveList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.proto.SceneObjMove.MseSceneObjMoveList.class, com.proto.SceneObjMove.MseSceneObjMoveList.Builder.class);
      }

      // Construct using com.proto.SceneObjMove.MseSceneObjMoveList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSceneObjMoveFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (sceneObjMoveBuilder_ == null) {
          sceneObjMove_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          sceneObjMoveBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.proto.SceneObjMove.internal_static_MseSceneObjMoveList_descriptor;
      }

      public com.proto.SceneObjMove.MseSceneObjMoveList getDefaultInstanceForType() {
        return com.proto.SceneObjMove.MseSceneObjMoveList.getDefaultInstance();
      }

      public com.proto.SceneObjMove.MseSceneObjMoveList build() {
        com.proto.SceneObjMove.MseSceneObjMoveList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.proto.SceneObjMove.MseSceneObjMoveList buildPartial() {
        com.proto.SceneObjMove.MseSceneObjMoveList result = new com.proto.SceneObjMove.MseSceneObjMoveList(this);
        int from_bitField0_ = bitField0_;
        if (sceneObjMoveBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            sceneObjMove_ = java.util.Collections.unmodifiableList(sceneObjMove_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.sceneObjMove_ = sceneObjMove_;
        } else {
          result.sceneObjMove_ = sceneObjMoveBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.proto.SceneObjMove.MseSceneObjMoveList) {
          return mergeFrom((com.proto.SceneObjMove.MseSceneObjMoveList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.proto.SceneObjMove.MseSceneObjMoveList other) {
        if (other == com.proto.SceneObjMove.MseSceneObjMoveList.getDefaultInstance()) return this;
        if (sceneObjMoveBuilder_ == null) {
          if (!other.sceneObjMove_.isEmpty()) {
            if (sceneObjMove_.isEmpty()) {
              sceneObjMove_ = other.sceneObjMove_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSceneObjMoveIsMutable();
              sceneObjMove_.addAll(other.sceneObjMove_);
            }
            onChanged();
          }
        } else {
          if (!other.sceneObjMove_.isEmpty()) {
            if (sceneObjMoveBuilder_.isEmpty()) {
              sceneObjMoveBuilder_.dispose();
              sceneObjMoveBuilder_ = null;
              sceneObjMove_ = other.sceneObjMove_;
              bitField0_ = (bitField0_ & ~0x00000001);
              sceneObjMoveBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSceneObjMoveFieldBuilder() : null;
            } else {
              sceneObjMoveBuilder_.addAllMessages(other.sceneObjMove_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getSceneObjMoveCount(); i++) {
          if (!getSceneObjMove(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.proto.SceneObjMove.MseSceneObjMoveList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.proto.SceneObjMove.MseSceneObjMoveList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.proto.SceneObjMove.MseSceneObjMove> sceneObjMove_ =
        java.util.Collections.emptyList();
      private void ensureSceneObjMoveIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          sceneObjMove_ = new java.util.ArrayList<com.proto.SceneObjMove.MseSceneObjMove>(sceneObjMove_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.proto.SceneObjMove.MseSceneObjMove, com.proto.SceneObjMove.MseSceneObjMove.Builder, com.proto.SceneObjMove.MseSceneObjMoveOrBuilder> sceneObjMoveBuilder_;

      /**
       * <code>repeated .MseSceneObjMove sceneObjMove = 1;</code>
       */
      public java.util.List<com.proto.SceneObjMove.MseSceneObjMove> getSceneObjMoveList() {
        if (sceneObjMoveBuilder_ == null) {
          return java.util.Collections.unmodifiableList(sceneObjMove_);
        } else {
          return sceneObjMoveBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .MseSceneObjMove sceneObjMove = 1;</code>
       */
      public int getSceneObjMoveCount() {
        if (sceneObjMoveBuilder_ == null) {
          return sceneObjMove_.size();
        } else {
          return sceneObjMoveBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .MseSceneObjMove sceneObjMove = 1;</code>
       */
      public com.proto.SceneObjMove.MseSceneObjMove getSceneObjMove(int index) {
        if (sceneObjMoveBuilder_ == null) {
          return sceneObjMove_.get(index);
        } else {
          return sceneObjMoveBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .MseSceneObjMove sceneObjMove = 1;</code>
       */
      public Builder setSceneObjMove(
          int index, com.proto.SceneObjMove.MseSceneObjMove value) {
        if (sceneObjMoveBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSceneObjMoveIsMutable();
          sceneObjMove_.set(index, value);
          onChanged();
        } else {
          sceneObjMoveBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MseSceneObjMove sceneObjMove = 1;</code>
       */
      public Builder setSceneObjMove(
          int index, com.proto.SceneObjMove.MseSceneObjMove.Builder builderForValue) {
        if (sceneObjMoveBuilder_ == null) {
          ensureSceneObjMoveIsMutable();
          sceneObjMove_.set(index, builderForValue.build());
          onChanged();
        } else {
          sceneObjMoveBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MseSceneObjMove sceneObjMove = 1;</code>
       */
      public Builder addSceneObjMove(com.proto.SceneObjMove.MseSceneObjMove value) {
        if (sceneObjMoveBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSceneObjMoveIsMutable();
          sceneObjMove_.add(value);
          onChanged();
        } else {
          sceneObjMoveBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .MseSceneObjMove sceneObjMove = 1;</code>
       */
      public Builder addSceneObjMove(
          int index, com.proto.SceneObjMove.MseSceneObjMove value) {
        if (sceneObjMoveBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSceneObjMoveIsMutable();
          sceneObjMove_.add(index, value);
          onChanged();
        } else {
          sceneObjMoveBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MseSceneObjMove sceneObjMove = 1;</code>
       */
      public Builder addSceneObjMove(
          com.proto.SceneObjMove.MseSceneObjMove.Builder builderForValue) {
        if (sceneObjMoveBuilder_ == null) {
          ensureSceneObjMoveIsMutable();
          sceneObjMove_.add(builderForValue.build());
          onChanged();
        } else {
          sceneObjMoveBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MseSceneObjMove sceneObjMove = 1;</code>
       */
      public Builder addSceneObjMove(
          int index, com.proto.SceneObjMove.MseSceneObjMove.Builder builderForValue) {
        if (sceneObjMoveBuilder_ == null) {
          ensureSceneObjMoveIsMutable();
          sceneObjMove_.add(index, builderForValue.build());
          onChanged();
        } else {
          sceneObjMoveBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MseSceneObjMove sceneObjMove = 1;</code>
       */
      public Builder addAllSceneObjMove(
          java.lang.Iterable<? extends com.proto.SceneObjMove.MseSceneObjMove> values) {
        if (sceneObjMoveBuilder_ == null) {
          ensureSceneObjMoveIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, sceneObjMove_);
          onChanged();
        } else {
          sceneObjMoveBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .MseSceneObjMove sceneObjMove = 1;</code>
       */
      public Builder clearSceneObjMove() {
        if (sceneObjMoveBuilder_ == null) {
          sceneObjMove_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          sceneObjMoveBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .MseSceneObjMove sceneObjMove = 1;</code>
       */
      public Builder removeSceneObjMove(int index) {
        if (sceneObjMoveBuilder_ == null) {
          ensureSceneObjMoveIsMutable();
          sceneObjMove_.remove(index);
          onChanged();
        } else {
          sceneObjMoveBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .MseSceneObjMove sceneObjMove = 1;</code>
       */
      public com.proto.SceneObjMove.MseSceneObjMove.Builder getSceneObjMoveBuilder(
          int index) {
        return getSceneObjMoveFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .MseSceneObjMove sceneObjMove = 1;</code>
       */
      public com.proto.SceneObjMove.MseSceneObjMoveOrBuilder getSceneObjMoveOrBuilder(
          int index) {
        if (sceneObjMoveBuilder_ == null) {
          return sceneObjMove_.get(index);  } else {
          return sceneObjMoveBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .MseSceneObjMove sceneObjMove = 1;</code>
       */
      public java.util.List<? extends com.proto.SceneObjMove.MseSceneObjMoveOrBuilder> 
           getSceneObjMoveOrBuilderList() {
        if (sceneObjMoveBuilder_ != null) {
          return sceneObjMoveBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(sceneObjMove_);
        }
      }
      /**
       * <code>repeated .MseSceneObjMove sceneObjMove = 1;</code>
       */
      public com.proto.SceneObjMove.MseSceneObjMove.Builder addSceneObjMoveBuilder() {
        return getSceneObjMoveFieldBuilder().addBuilder(
            com.proto.SceneObjMove.MseSceneObjMove.getDefaultInstance());
      }
      /**
       * <code>repeated .MseSceneObjMove sceneObjMove = 1;</code>
       */
      public com.proto.SceneObjMove.MseSceneObjMove.Builder addSceneObjMoveBuilder(
          int index) {
        return getSceneObjMoveFieldBuilder().addBuilder(
            index, com.proto.SceneObjMove.MseSceneObjMove.getDefaultInstance());
      }
      /**
       * <code>repeated .MseSceneObjMove sceneObjMove = 1;</code>
       */
      public java.util.List<com.proto.SceneObjMove.MseSceneObjMove.Builder> 
           getSceneObjMoveBuilderList() {
        return getSceneObjMoveFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.proto.SceneObjMove.MseSceneObjMove, com.proto.SceneObjMove.MseSceneObjMove.Builder, com.proto.SceneObjMove.MseSceneObjMoveOrBuilder> 
          getSceneObjMoveFieldBuilder() {
        if (sceneObjMoveBuilder_ == null) {
          sceneObjMoveBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.proto.SceneObjMove.MseSceneObjMove, com.proto.SceneObjMove.MseSceneObjMove.Builder, com.proto.SceneObjMove.MseSceneObjMoveOrBuilder>(
                  sceneObjMove_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          sceneObjMove_ = null;
        }
        return sceneObjMoveBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MseSceneObjMoveList)
    }

    // @@protoc_insertion_point(class_scope:MseSceneObjMoveList)
    private static final com.proto.SceneObjMove.MseSceneObjMoveList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.proto.SceneObjMove.MseSceneObjMoveList();
    }

    public static com.proto.SceneObjMove.MseSceneObjMoveList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MseSceneObjMoveList>
        PARSER = new com.google.protobuf.AbstractParser<MseSceneObjMoveList>() {
      public MseSceneObjMoveList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MseSceneObjMoveList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MseSceneObjMoveList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MseSceneObjMoveList> getParserForType() {
      return PARSER;
    }

    public com.proto.SceneObjMove.MseSceneObjMoveList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MseSceneObjMove_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MseSceneObjMove_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MseSceneObjMoveList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MseSceneObjMoveList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022SceneObjMove.proto\"\232\001\n\017MseSceneObjMove" +
      "\022\013\n\003uid\030\001 \002(\t\022 \n\006status\030\002 \002(\0162\020.E_SceneO" +
      "bjMoveS\022\017\n\007endTime\030\003 \002(\003\022\014\n\004posX\030\004 \001(\002\022\014" +
      "\n\004posY\030\005 \001(\002\022\025\n\rcurrentDegree\030\006 \001(\002\022\024\n\014t" +
      "argetDegree\030\007 \001(\002\"=\n\023MseSceneObjMoveList" +
      "\022&\n\014sceneObjMove\030\001 \003(\0132\020.MseSceneObjMove" +
      "*O\n\017E_SceneObjMoveS\022\010\n\004STOP\020\001\022\023\n\017STOP_AN" +
      "D_ROTATE\020\002\022\010\n\004MOVE\020\003\022\023\n\017MOVE_AND_ROTATE\020" +
      "\004B\031\n\tcom.protoB\014SceneObjMove"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MseSceneObjMove_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MseSceneObjMove_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MseSceneObjMove_descriptor,
        new java.lang.String[] { "Uid", "Status", "EndTime", "PosX", "PosY", "CurrentDegree", "TargetDegree", });
    internal_static_MseSceneObjMoveList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MseSceneObjMoveList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MseSceneObjMoveList_descriptor,
        new java.lang.String[] { "SceneObjMove", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
