// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SceneObjAppear.proto

package com.proto;

public final class SceneObjAppear {
  private SceneObjAppear() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MseSceneObjAppearOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MseSceneObjAppear)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string uid = 1;</code>
     */
    boolean hasUid();
    /**
     * <code>required string uid = 1;</code>
     */
    java.lang.String getUid();
    /**
     * <code>required string uid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUidBytes();

    /**
     * <code>required float x = 2;</code>
     */
    boolean hasX();
    /**
     * <code>required float x = 2;</code>
     */
    float getX();

    /**
     * <code>required float y = 3;</code>
     */
    boolean hasY();
    /**
     * <code>required float y = 3;</code>
     */
    float getY();

    /**
     * <pre>
     * 角度
     * </pre>
     *
     * <code>required float degree = 4;</code>
     */
    boolean hasDegree();
    /**
     * <pre>
     * 角度
     * </pre>
     *
     * <code>required float degree = 4;</code>
     */
    float getDegree();

    /**
     * <code>required float speed = 5;</code>
     */
    boolean hasSpeed();
    /**
     * <code>required float speed = 5;</code>
     */
    float getSpeed();

    /**
     * <code>required float degreeSpeed = 6;</code>
     */
    boolean hasDegreeSpeed();
    /**
     * <code>required float degreeSpeed = 6;</code>
     */
    float getDegreeSpeed();
  }
  /**
   * <pre>
   *场景中的怪物信息
   * </pre>
   *
   * Protobuf type {@code MseSceneObjAppear}
   */
  public  static final class MseSceneObjAppear extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MseSceneObjAppear)
      MseSceneObjAppearOrBuilder {
    // Use MseSceneObjAppear.newBuilder() to construct.
    private MseSceneObjAppear(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MseSceneObjAppear() {
      uid_ = "";
      x_ = 0F;
      y_ = 0F;
      degree_ = 0F;
      speed_ = 0F;
      degreeSpeed_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MseSceneObjAppear(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              uid_ = bs;
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              x_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              y_ = input.readFloat();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              degree_ = input.readFloat();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000010;
              speed_ = input.readFloat();
              break;
            }
            case 53: {
              bitField0_ |= 0x00000020;
              degreeSpeed_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.proto.SceneObjAppear.internal_static_MseSceneObjAppear_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.proto.SceneObjAppear.internal_static_MseSceneObjAppear_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.proto.SceneObjAppear.MseSceneObjAppear.class, com.proto.SceneObjAppear.MseSceneObjAppear.Builder.class);
    }

    private int bitField0_;
    public static final int UID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uid_;
    /**
     * <code>required string uid = 1;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string uid = 1;</code>
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string uid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int X_FIELD_NUMBER = 2;
    private float x_;
    /**
     * <code>required float x = 2;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float x = 2;</code>
     */
    public float getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 3;
    private float y_;
    /**
     * <code>required float y = 3;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required float y = 3;</code>
     */
    public float getY() {
      return y_;
    }

    public static final int DEGREE_FIELD_NUMBER = 4;
    private float degree_;
    /**
     * <pre>
     * 角度
     * </pre>
     *
     * <code>required float degree = 4;</code>
     */
    public boolean hasDegree() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * 角度
     * </pre>
     *
     * <code>required float degree = 4;</code>
     */
    public float getDegree() {
      return degree_;
    }

    public static final int SPEED_FIELD_NUMBER = 5;
    private float speed_;
    /**
     * <code>required float speed = 5;</code>
     */
    public boolean hasSpeed() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required float speed = 5;</code>
     */
    public float getSpeed() {
      return speed_;
    }

    public static final int DEGREESPEED_FIELD_NUMBER = 6;
    private float degreeSpeed_;
    /**
     * <code>required float degreeSpeed = 6;</code>
     */
    public boolean hasDegreeSpeed() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required float degreeSpeed = 6;</code>
     */
    public float getDegreeSpeed() {
      return degreeSpeed_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDegree()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSpeed()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDegreeSpeed()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, x_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, y_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, degree_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeFloat(5, speed_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeFloat(6, degreeSpeed_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, x_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, y_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, degree_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, speed_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, degreeSpeed_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.proto.SceneObjAppear.MseSceneObjAppear)) {
        return super.equals(obj);
      }
      com.proto.SceneObjAppear.MseSceneObjAppear other = (com.proto.SceneObjAppear.MseSceneObjAppear) obj;

      boolean result = true;
      result = result && (hasUid() == other.hasUid());
      if (hasUid()) {
        result = result && getUid()
            .equals(other.getUid());
      }
      result = result && (hasX() == other.hasX());
      if (hasX()) {
        result = result && (
            java.lang.Float.floatToIntBits(getX())
            == java.lang.Float.floatToIntBits(
                other.getX()));
      }
      result = result && (hasY() == other.hasY());
      if (hasY()) {
        result = result && (
            java.lang.Float.floatToIntBits(getY())
            == java.lang.Float.floatToIntBits(
                other.getY()));
      }
      result = result && (hasDegree() == other.hasDegree());
      if (hasDegree()) {
        result = result && (
            java.lang.Float.floatToIntBits(getDegree())
            == java.lang.Float.floatToIntBits(
                other.getDegree()));
      }
      result = result && (hasSpeed() == other.hasSpeed());
      if (hasSpeed()) {
        result = result && (
            java.lang.Float.floatToIntBits(getSpeed())
            == java.lang.Float.floatToIntBits(
                other.getSpeed()));
      }
      result = result && (hasDegreeSpeed() == other.hasDegreeSpeed());
      if (hasDegreeSpeed()) {
        result = result && (
            java.lang.Float.floatToIntBits(getDegreeSpeed())
            == java.lang.Float.floatToIntBits(
                other.getDegreeSpeed()));
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasUid()) {
        hash = (37 * hash) + UID_FIELD_NUMBER;
        hash = (53 * hash) + getUid().hashCode();
      }
      if (hasX()) {
        hash = (37 * hash) + X_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getX());
      }
      if (hasY()) {
        hash = (37 * hash) + Y_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getY());
      }
      if (hasDegree()) {
        hash = (37 * hash) + DEGREE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getDegree());
      }
      if (hasSpeed()) {
        hash = (37 * hash) + SPEED_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getSpeed());
      }
      if (hasDegreeSpeed()) {
        hash = (37 * hash) + DEGREESPEED_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getDegreeSpeed());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.proto.SceneObjAppear.MseSceneObjAppear parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.SceneObjAppear.MseSceneObjAppear parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.SceneObjAppear.MseSceneObjAppear parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.SceneObjAppear.MseSceneObjAppear parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.SceneObjAppear.MseSceneObjAppear parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.proto.SceneObjAppear.MseSceneObjAppear parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.proto.SceneObjAppear.MseSceneObjAppear parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.proto.SceneObjAppear.MseSceneObjAppear parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.proto.SceneObjAppear.MseSceneObjAppear parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.proto.SceneObjAppear.MseSceneObjAppear parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.proto.SceneObjAppear.MseSceneObjAppear prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *场景中的怪物信息
     * </pre>
     *
     * Protobuf type {@code MseSceneObjAppear}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MseSceneObjAppear)
        com.proto.SceneObjAppear.MseSceneObjAppearOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.proto.SceneObjAppear.internal_static_MseSceneObjAppear_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.proto.SceneObjAppear.internal_static_MseSceneObjAppear_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.proto.SceneObjAppear.MseSceneObjAppear.class, com.proto.SceneObjAppear.MseSceneObjAppear.Builder.class);
      }

      // Construct using com.proto.SceneObjAppear.MseSceneObjAppear.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        degree_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        speed_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        degreeSpeed_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.proto.SceneObjAppear.internal_static_MseSceneObjAppear_descriptor;
      }

      public com.proto.SceneObjAppear.MseSceneObjAppear getDefaultInstanceForType() {
        return com.proto.SceneObjAppear.MseSceneObjAppear.getDefaultInstance();
      }

      public com.proto.SceneObjAppear.MseSceneObjAppear build() {
        com.proto.SceneObjAppear.MseSceneObjAppear result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.proto.SceneObjAppear.MseSceneObjAppear buildPartial() {
        com.proto.SceneObjAppear.MseSceneObjAppear result = new com.proto.SceneObjAppear.MseSceneObjAppear(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.degree_ = degree_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.speed_ = speed_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.degreeSpeed_ = degreeSpeed_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.proto.SceneObjAppear.MseSceneObjAppear) {
          return mergeFrom((com.proto.SceneObjAppear.MseSceneObjAppear)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.proto.SceneObjAppear.MseSceneObjAppear other) {
        if (other == com.proto.SceneObjAppear.MseSceneObjAppear.getDefaultInstance()) return this;
        if (other.hasUid()) {
          bitField0_ |= 0x00000001;
          uid_ = other.uid_;
          onChanged();
        }
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasDegree()) {
          setDegree(other.getDegree());
        }
        if (other.hasSpeed()) {
          setSpeed(other.getSpeed());
        }
        if (other.hasDegreeSpeed()) {
          setDegreeSpeed(other.getDegreeSpeed());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUid()) {
          return false;
        }
        if (!hasX()) {
          return false;
        }
        if (!hasY()) {
          return false;
        }
        if (!hasDegree()) {
          return false;
        }
        if (!hasSpeed()) {
          return false;
        }
        if (!hasDegreeSpeed()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.proto.SceneObjAppear.MseSceneObjAppear parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.proto.SceneObjAppear.MseSceneObjAppear) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object uid_ = "";
      /**
       * <code>required string uid = 1;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string uid = 1;</code>
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string uid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string uid = 1;</code>
       */
      public Builder setUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string uid = 1;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <code>required string uid = 1;</code>
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }

      private float x_ ;
      /**
       * <code>required float x = 2;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float x = 2;</code>
       */
      public float getX() {
        return x_;
      }
      /**
       * <code>required float x = 2;</code>
       */
      public Builder setX(float value) {
        bitField0_ |= 0x00000002;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float x = 2;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        x_ = 0F;
        onChanged();
        return this;
      }

      private float y_ ;
      /**
       * <code>required float y = 3;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required float y = 3;</code>
       */
      public float getY() {
        return y_;
      }
      /**
       * <code>required float y = 3;</code>
       */
      public Builder setY(float value) {
        bitField0_ |= 0x00000004;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float y = 3;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        y_ = 0F;
        onChanged();
        return this;
      }

      private float degree_ ;
      /**
       * <pre>
       * 角度
       * </pre>
       *
       * <code>required float degree = 4;</code>
       */
      public boolean hasDegree() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       * 角度
       * </pre>
       *
       * <code>required float degree = 4;</code>
       */
      public float getDegree() {
        return degree_;
      }
      /**
       * <pre>
       * 角度
       * </pre>
       *
       * <code>required float degree = 4;</code>
       */
      public Builder setDegree(float value) {
        bitField0_ |= 0x00000008;
        degree_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 角度
       * </pre>
       *
       * <code>required float degree = 4;</code>
       */
      public Builder clearDegree() {
        bitField0_ = (bitField0_ & ~0x00000008);
        degree_ = 0F;
        onChanged();
        return this;
      }

      private float speed_ ;
      /**
       * <code>required float speed = 5;</code>
       */
      public boolean hasSpeed() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required float speed = 5;</code>
       */
      public float getSpeed() {
        return speed_;
      }
      /**
       * <code>required float speed = 5;</code>
       */
      public Builder setSpeed(float value) {
        bitField0_ |= 0x00000010;
        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float speed = 5;</code>
       */
      public Builder clearSpeed() {
        bitField0_ = (bitField0_ & ~0x00000010);
        speed_ = 0F;
        onChanged();
        return this;
      }

      private float degreeSpeed_ ;
      /**
       * <code>required float degreeSpeed = 6;</code>
       */
      public boolean hasDegreeSpeed() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required float degreeSpeed = 6;</code>
       */
      public float getDegreeSpeed() {
        return degreeSpeed_;
      }
      /**
       * <code>required float degreeSpeed = 6;</code>
       */
      public Builder setDegreeSpeed(float value) {
        bitField0_ |= 0x00000020;
        degreeSpeed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float degreeSpeed = 6;</code>
       */
      public Builder clearDegreeSpeed() {
        bitField0_ = (bitField0_ & ~0x00000020);
        degreeSpeed_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MseSceneObjAppear)
    }

    // @@protoc_insertion_point(class_scope:MseSceneObjAppear)
    private static final com.proto.SceneObjAppear.MseSceneObjAppear DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.proto.SceneObjAppear.MseSceneObjAppear();
    }

    public static com.proto.SceneObjAppear.MseSceneObjAppear getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MseSceneObjAppear>
        PARSER = new com.google.protobuf.AbstractParser<MseSceneObjAppear>() {
      public MseSceneObjAppear parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MseSceneObjAppear(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MseSceneObjAppear> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MseSceneObjAppear> getParserForType() {
      return PARSER;
    }

    public com.proto.SceneObjAppear.MseSceneObjAppear getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MseSceneObjAppearListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MseSceneObjAppearList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .MseSceneObjAppear sceneObjAppear = 1;</code>
     */
    java.util.List<com.proto.SceneObjAppear.MseSceneObjAppear> 
        getSceneObjAppearList();
    /**
     * <code>repeated .MseSceneObjAppear sceneObjAppear = 1;</code>
     */
    com.proto.SceneObjAppear.MseSceneObjAppear getSceneObjAppear(int index);
    /**
     * <code>repeated .MseSceneObjAppear sceneObjAppear = 1;</code>
     */
    int getSceneObjAppearCount();
    /**
     * <code>repeated .MseSceneObjAppear sceneObjAppear = 1;</code>
     */
    java.util.List<? extends com.proto.SceneObjAppear.MseSceneObjAppearOrBuilder> 
        getSceneObjAppearOrBuilderList();
    /**
     * <code>repeated .MseSceneObjAppear sceneObjAppear = 1;</code>
     */
    com.proto.SceneObjAppear.MseSceneObjAppearOrBuilder getSceneObjAppearOrBuilder(
        int index);
  }
  /**
   * <pre>
   * 场景中的怪物列表
   * </pre>
   *
   * Protobuf type {@code MseSceneObjAppearList}
   */
  public  static final class MseSceneObjAppearList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MseSceneObjAppearList)
      MseSceneObjAppearListOrBuilder {
    // Use MseSceneObjAppearList.newBuilder() to construct.
    private MseSceneObjAppearList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MseSceneObjAppearList() {
      sceneObjAppear_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MseSceneObjAppearList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                sceneObjAppear_ = new java.util.ArrayList<com.proto.SceneObjAppear.MseSceneObjAppear>();
                mutable_bitField0_ |= 0x00000001;
              }
              sceneObjAppear_.add(
                  input.readMessage(com.proto.SceneObjAppear.MseSceneObjAppear.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          sceneObjAppear_ = java.util.Collections.unmodifiableList(sceneObjAppear_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.proto.SceneObjAppear.internal_static_MseSceneObjAppearList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.proto.SceneObjAppear.internal_static_MseSceneObjAppearList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.proto.SceneObjAppear.MseSceneObjAppearList.class, com.proto.SceneObjAppear.MseSceneObjAppearList.Builder.class);
    }

    public static final int SCENEOBJAPPEAR_FIELD_NUMBER = 1;
    private java.util.List<com.proto.SceneObjAppear.MseSceneObjAppear> sceneObjAppear_;
    /**
     * <code>repeated .MseSceneObjAppear sceneObjAppear = 1;</code>
     */
    public java.util.List<com.proto.SceneObjAppear.MseSceneObjAppear> getSceneObjAppearList() {
      return sceneObjAppear_;
    }
    /**
     * <code>repeated .MseSceneObjAppear sceneObjAppear = 1;</code>
     */
    public java.util.List<? extends com.proto.SceneObjAppear.MseSceneObjAppearOrBuilder> 
        getSceneObjAppearOrBuilderList() {
      return sceneObjAppear_;
    }
    /**
     * <code>repeated .MseSceneObjAppear sceneObjAppear = 1;</code>
     */
    public int getSceneObjAppearCount() {
      return sceneObjAppear_.size();
    }
    /**
     * <code>repeated .MseSceneObjAppear sceneObjAppear = 1;</code>
     */
    public com.proto.SceneObjAppear.MseSceneObjAppear getSceneObjAppear(int index) {
      return sceneObjAppear_.get(index);
    }
    /**
     * <code>repeated .MseSceneObjAppear sceneObjAppear = 1;</code>
     */
    public com.proto.SceneObjAppear.MseSceneObjAppearOrBuilder getSceneObjAppearOrBuilder(
        int index) {
      return sceneObjAppear_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getSceneObjAppearCount(); i++) {
        if (!getSceneObjAppear(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < sceneObjAppear_.size(); i++) {
        output.writeMessage(1, sceneObjAppear_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < sceneObjAppear_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, sceneObjAppear_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.proto.SceneObjAppear.MseSceneObjAppearList)) {
        return super.equals(obj);
      }
      com.proto.SceneObjAppear.MseSceneObjAppearList other = (com.proto.SceneObjAppear.MseSceneObjAppearList) obj;

      boolean result = true;
      result = result && getSceneObjAppearList()
          .equals(other.getSceneObjAppearList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getSceneObjAppearCount() > 0) {
        hash = (37 * hash) + SCENEOBJAPPEAR_FIELD_NUMBER;
        hash = (53 * hash) + getSceneObjAppearList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.proto.SceneObjAppear.MseSceneObjAppearList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.SceneObjAppear.MseSceneObjAppearList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.SceneObjAppear.MseSceneObjAppearList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.SceneObjAppear.MseSceneObjAppearList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.SceneObjAppear.MseSceneObjAppearList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.proto.SceneObjAppear.MseSceneObjAppearList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.proto.SceneObjAppear.MseSceneObjAppearList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.proto.SceneObjAppear.MseSceneObjAppearList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.proto.SceneObjAppear.MseSceneObjAppearList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.proto.SceneObjAppear.MseSceneObjAppearList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.proto.SceneObjAppear.MseSceneObjAppearList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 场景中的怪物列表
     * </pre>
     *
     * Protobuf type {@code MseSceneObjAppearList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MseSceneObjAppearList)
        com.proto.SceneObjAppear.MseSceneObjAppearListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.proto.SceneObjAppear.internal_static_MseSceneObjAppearList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.proto.SceneObjAppear.internal_static_MseSceneObjAppearList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.proto.SceneObjAppear.MseSceneObjAppearList.class, com.proto.SceneObjAppear.MseSceneObjAppearList.Builder.class);
      }

      // Construct using com.proto.SceneObjAppear.MseSceneObjAppearList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSceneObjAppearFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (sceneObjAppearBuilder_ == null) {
          sceneObjAppear_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          sceneObjAppearBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.proto.SceneObjAppear.internal_static_MseSceneObjAppearList_descriptor;
      }

      public com.proto.SceneObjAppear.MseSceneObjAppearList getDefaultInstanceForType() {
        return com.proto.SceneObjAppear.MseSceneObjAppearList.getDefaultInstance();
      }

      public com.proto.SceneObjAppear.MseSceneObjAppearList build() {
        com.proto.SceneObjAppear.MseSceneObjAppearList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.proto.SceneObjAppear.MseSceneObjAppearList buildPartial() {
        com.proto.SceneObjAppear.MseSceneObjAppearList result = new com.proto.SceneObjAppear.MseSceneObjAppearList(this);
        int from_bitField0_ = bitField0_;
        if (sceneObjAppearBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            sceneObjAppear_ = java.util.Collections.unmodifiableList(sceneObjAppear_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.sceneObjAppear_ = sceneObjAppear_;
        } else {
          result.sceneObjAppear_ = sceneObjAppearBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.proto.SceneObjAppear.MseSceneObjAppearList) {
          return mergeFrom((com.proto.SceneObjAppear.MseSceneObjAppearList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.proto.SceneObjAppear.MseSceneObjAppearList other) {
        if (other == com.proto.SceneObjAppear.MseSceneObjAppearList.getDefaultInstance()) return this;
        if (sceneObjAppearBuilder_ == null) {
          if (!other.sceneObjAppear_.isEmpty()) {
            if (sceneObjAppear_.isEmpty()) {
              sceneObjAppear_ = other.sceneObjAppear_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSceneObjAppearIsMutable();
              sceneObjAppear_.addAll(other.sceneObjAppear_);
            }
            onChanged();
          }
        } else {
          if (!other.sceneObjAppear_.isEmpty()) {
            if (sceneObjAppearBuilder_.isEmpty()) {
              sceneObjAppearBuilder_.dispose();
              sceneObjAppearBuilder_ = null;
              sceneObjAppear_ = other.sceneObjAppear_;
              bitField0_ = (bitField0_ & ~0x00000001);
              sceneObjAppearBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSceneObjAppearFieldBuilder() : null;
            } else {
              sceneObjAppearBuilder_.addAllMessages(other.sceneObjAppear_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getSceneObjAppearCount(); i++) {
          if (!getSceneObjAppear(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.proto.SceneObjAppear.MseSceneObjAppearList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.proto.SceneObjAppear.MseSceneObjAppearList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.proto.SceneObjAppear.MseSceneObjAppear> sceneObjAppear_ =
        java.util.Collections.emptyList();
      private void ensureSceneObjAppearIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          sceneObjAppear_ = new java.util.ArrayList<com.proto.SceneObjAppear.MseSceneObjAppear>(sceneObjAppear_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.proto.SceneObjAppear.MseSceneObjAppear, com.proto.SceneObjAppear.MseSceneObjAppear.Builder, com.proto.SceneObjAppear.MseSceneObjAppearOrBuilder> sceneObjAppearBuilder_;

      /**
       * <code>repeated .MseSceneObjAppear sceneObjAppear = 1;</code>
       */
      public java.util.List<com.proto.SceneObjAppear.MseSceneObjAppear> getSceneObjAppearList() {
        if (sceneObjAppearBuilder_ == null) {
          return java.util.Collections.unmodifiableList(sceneObjAppear_);
        } else {
          return sceneObjAppearBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .MseSceneObjAppear sceneObjAppear = 1;</code>
       */
      public int getSceneObjAppearCount() {
        if (sceneObjAppearBuilder_ == null) {
          return sceneObjAppear_.size();
        } else {
          return sceneObjAppearBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .MseSceneObjAppear sceneObjAppear = 1;</code>
       */
      public com.proto.SceneObjAppear.MseSceneObjAppear getSceneObjAppear(int index) {
        if (sceneObjAppearBuilder_ == null) {
          return sceneObjAppear_.get(index);
        } else {
          return sceneObjAppearBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .MseSceneObjAppear sceneObjAppear = 1;</code>
       */
      public Builder setSceneObjAppear(
          int index, com.proto.SceneObjAppear.MseSceneObjAppear value) {
        if (sceneObjAppearBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSceneObjAppearIsMutable();
          sceneObjAppear_.set(index, value);
          onChanged();
        } else {
          sceneObjAppearBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MseSceneObjAppear sceneObjAppear = 1;</code>
       */
      public Builder setSceneObjAppear(
          int index, com.proto.SceneObjAppear.MseSceneObjAppear.Builder builderForValue) {
        if (sceneObjAppearBuilder_ == null) {
          ensureSceneObjAppearIsMutable();
          sceneObjAppear_.set(index, builderForValue.build());
          onChanged();
        } else {
          sceneObjAppearBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MseSceneObjAppear sceneObjAppear = 1;</code>
       */
      public Builder addSceneObjAppear(com.proto.SceneObjAppear.MseSceneObjAppear value) {
        if (sceneObjAppearBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSceneObjAppearIsMutable();
          sceneObjAppear_.add(value);
          onChanged();
        } else {
          sceneObjAppearBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .MseSceneObjAppear sceneObjAppear = 1;</code>
       */
      public Builder addSceneObjAppear(
          int index, com.proto.SceneObjAppear.MseSceneObjAppear value) {
        if (sceneObjAppearBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSceneObjAppearIsMutable();
          sceneObjAppear_.add(index, value);
          onChanged();
        } else {
          sceneObjAppearBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MseSceneObjAppear sceneObjAppear = 1;</code>
       */
      public Builder addSceneObjAppear(
          com.proto.SceneObjAppear.MseSceneObjAppear.Builder builderForValue) {
        if (sceneObjAppearBuilder_ == null) {
          ensureSceneObjAppearIsMutable();
          sceneObjAppear_.add(builderForValue.build());
          onChanged();
        } else {
          sceneObjAppearBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MseSceneObjAppear sceneObjAppear = 1;</code>
       */
      public Builder addSceneObjAppear(
          int index, com.proto.SceneObjAppear.MseSceneObjAppear.Builder builderForValue) {
        if (sceneObjAppearBuilder_ == null) {
          ensureSceneObjAppearIsMutable();
          sceneObjAppear_.add(index, builderForValue.build());
          onChanged();
        } else {
          sceneObjAppearBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MseSceneObjAppear sceneObjAppear = 1;</code>
       */
      public Builder addAllSceneObjAppear(
          java.lang.Iterable<? extends com.proto.SceneObjAppear.MseSceneObjAppear> values) {
        if (sceneObjAppearBuilder_ == null) {
          ensureSceneObjAppearIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, sceneObjAppear_);
          onChanged();
        } else {
          sceneObjAppearBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .MseSceneObjAppear sceneObjAppear = 1;</code>
       */
      public Builder clearSceneObjAppear() {
        if (sceneObjAppearBuilder_ == null) {
          sceneObjAppear_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          sceneObjAppearBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .MseSceneObjAppear sceneObjAppear = 1;</code>
       */
      public Builder removeSceneObjAppear(int index) {
        if (sceneObjAppearBuilder_ == null) {
          ensureSceneObjAppearIsMutable();
          sceneObjAppear_.remove(index);
          onChanged();
        } else {
          sceneObjAppearBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .MseSceneObjAppear sceneObjAppear = 1;</code>
       */
      public com.proto.SceneObjAppear.MseSceneObjAppear.Builder getSceneObjAppearBuilder(
          int index) {
        return getSceneObjAppearFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .MseSceneObjAppear sceneObjAppear = 1;</code>
       */
      public com.proto.SceneObjAppear.MseSceneObjAppearOrBuilder getSceneObjAppearOrBuilder(
          int index) {
        if (sceneObjAppearBuilder_ == null) {
          return sceneObjAppear_.get(index);  } else {
          return sceneObjAppearBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .MseSceneObjAppear sceneObjAppear = 1;</code>
       */
      public java.util.List<? extends com.proto.SceneObjAppear.MseSceneObjAppearOrBuilder> 
           getSceneObjAppearOrBuilderList() {
        if (sceneObjAppearBuilder_ != null) {
          return sceneObjAppearBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(sceneObjAppear_);
        }
      }
      /**
       * <code>repeated .MseSceneObjAppear sceneObjAppear = 1;</code>
       */
      public com.proto.SceneObjAppear.MseSceneObjAppear.Builder addSceneObjAppearBuilder() {
        return getSceneObjAppearFieldBuilder().addBuilder(
            com.proto.SceneObjAppear.MseSceneObjAppear.getDefaultInstance());
      }
      /**
       * <code>repeated .MseSceneObjAppear sceneObjAppear = 1;</code>
       */
      public com.proto.SceneObjAppear.MseSceneObjAppear.Builder addSceneObjAppearBuilder(
          int index) {
        return getSceneObjAppearFieldBuilder().addBuilder(
            index, com.proto.SceneObjAppear.MseSceneObjAppear.getDefaultInstance());
      }
      /**
       * <code>repeated .MseSceneObjAppear sceneObjAppear = 1;</code>
       */
      public java.util.List<com.proto.SceneObjAppear.MseSceneObjAppear.Builder> 
           getSceneObjAppearBuilderList() {
        return getSceneObjAppearFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.proto.SceneObjAppear.MseSceneObjAppear, com.proto.SceneObjAppear.MseSceneObjAppear.Builder, com.proto.SceneObjAppear.MseSceneObjAppearOrBuilder> 
          getSceneObjAppearFieldBuilder() {
        if (sceneObjAppearBuilder_ == null) {
          sceneObjAppearBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.proto.SceneObjAppear.MseSceneObjAppear, com.proto.SceneObjAppear.MseSceneObjAppear.Builder, com.proto.SceneObjAppear.MseSceneObjAppearOrBuilder>(
                  sceneObjAppear_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          sceneObjAppear_ = null;
        }
        return sceneObjAppearBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MseSceneObjAppearList)
    }

    // @@protoc_insertion_point(class_scope:MseSceneObjAppearList)
    private static final com.proto.SceneObjAppear.MseSceneObjAppearList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.proto.SceneObjAppear.MseSceneObjAppearList();
    }

    public static com.proto.SceneObjAppear.MseSceneObjAppearList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MseSceneObjAppearList>
        PARSER = new com.google.protobuf.AbstractParser<MseSceneObjAppearList>() {
      public MseSceneObjAppearList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MseSceneObjAppearList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MseSceneObjAppearList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MseSceneObjAppearList> getParserForType() {
      return PARSER;
    }

    public com.proto.SceneObjAppear.MseSceneObjAppearList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MseSceneObjAppear_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MseSceneObjAppear_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MseSceneObjAppearList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MseSceneObjAppearList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024SceneObjAppear.proto\"j\n\021MseSceneObjApp" +
      "ear\022\013\n\003uid\030\001 \002(\t\022\t\n\001x\030\002 \002(\002\022\t\n\001y\030\003 \002(\002\022\016" +
      "\n\006degree\030\004 \002(\002\022\r\n\005speed\030\005 \002(\002\022\023\n\013degreeS" +
      "peed\030\006 \002(\002\"C\n\025MseSceneObjAppearList\022*\n\016s" +
      "ceneObjAppear\030\001 \003(\0132\022.MseSceneObjAppearB" +
      "\033\n\tcom.protoB\016SceneObjAppear"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MseSceneObjAppear_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MseSceneObjAppear_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MseSceneObjAppear_descriptor,
        new java.lang.String[] { "Uid", "X", "Y", "Degree", "Speed", "DegreeSpeed", });
    internal_static_MseSceneObjAppearList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MseSceneObjAppearList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MseSceneObjAppearList_descriptor,
        new java.lang.String[] { "SceneObjAppear", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
